from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class OperationStatus(str, Enum):
    PASS="PASS"; BLOCK="BLOCK"; NOT_RUN="NOT_RUN"; MANUAL_REVIEW="MANUAL_REVIEW"


class ObservationClassification(str, Enum):
    BUILD_SUCCEEDED="BUILD_SUCCEEDED"; BUILD_FAILED="BUILD_FAILED"; DEPENDENCY_MISSING="DEPENDENCY_MISSING"; TOOLCHAIN_MISSING="TOOLCHAIN_MISSING"; COMPILER_MISSING="COMPILER_MISSING"; BACKEND_DEPENDENCY_MISSING="BACKEND_DEPENDENCY_MISSING"; SYSTEM_LIBRARY_MISSING="SYSTEM_LIBRARY_MISSING"; RUNTIME_INCOMPATIBLE="RUNTIME_INCOMPATIBLE"; INCONCLUSIVE="INCONCLUSIVE"; NOT_APPLICABLE="NOT_APPLICABLE"; SECURITY_BLOCK="SECURITY_BLOCK"


class HypothesisStatus(str, Enum):
    UNTESTED="UNTESTED"; SUPPORTED="SUPPORTED"; REFUTED="REFUTED"; PARTIALLY_SUPPORTED="PARTIALLY_SUPPORTED"; INCONCLUSIVE="INCONCLUSIVE"; CONFLICTED="CONFLICTED"


class BranchStatus(str, Enum):
    OPEN="OPEN"; CAUSE_ISOLATED="CAUSE_ISOLATED"; REMEDIATION_PENDING="REMEDIATION_PENDING"; REMEDIATION_VERIFIED="REMEDIATION_VERIFIED"; CLOSED="CLOSED"; BLOCKED="BLOCKED"; CONFLICTED="CONFLICTED"; RETIRED="RETIRED"


@dataclass(frozen=True)
class SemanticObservation:
    operation_status: str
    observation_classification: str
    hypothesis_state: str
    branch_state: str
    blocker: str | None = None
