from __future__ import annotations
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DEFAULT=ROOT/"outputs/post_v2_37_hardening_batch102_fresh_exact_counterfactual_execution_necessity_sufficiency_ownership_closure"
def jl(path):return [json.loads(x) for x in path.read_text(encoding="utf-8").splitlines() if x]
def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--output-root",type=Path,default=DEFAULT);a=p.parse_args();errors=[]
 required=["batch101_execution_origin_correction_receipt.json","batch102_pre_fresh_execution_expected_failure.json","batch102_consolidated_state.json","batch102_claim_boundary.json","batch102_fresh_execution_origin_audit.json","batch102_registered_cell_ledger_v4.jsonl","batch102_controller_audit_terminal_records_v5.jsonl","batch102_independent_critic_summary.json","batch102_architecture_gain_gate_v4.json","batch102_unselected_outcome_access_audit_v3.json"]
 for name in required:
  if not (a.output_root/name).is_file():errors.append("missing:"+name)
 if errors:print(json.dumps({"status":"BLOCK","errors":errors},sort_keys=True));return 1
 origin=json.loads((a.output_root/"batch101_execution_origin_correction_receipt.json").read_text(encoding="utf-8"));red=json.loads((a.output_root/"batch102_pre_fresh_execution_expected_failure.json").read_text(encoding="utf-8"));claim=json.loads((a.output_root/"batch102_claim_boundary.json").read_text(encoding="utf-8"));state=json.loads((a.output_root/"batch102_consolidated_state.json").read_text(encoding="utf-8"));fresh=json.loads((a.output_root/"batch102_fresh_execution_origin_audit.json").read_text(encoding="utf-8"));critic=json.loads((a.output_root/"batch102_independent_critic_summary.json").read_text(encoding="utf-8"));vault=json.loads((a.output_root/"batch102_unselected_outcome_access_audit_v3.json").read_text(encoding="utf-8"));cells=jl(a.output_root/"batch102_registered_cell_ledger_v4.jsonl");terminals=jl(a.output_root/"batch102_controller_audit_terminal_records_v5.jsonl")
 checks={"Batch101_origin_corrected":origin.get("fresh_Batch101_candidate_operation_count")==0 and origin.get("inherited_Batch100_raw_replay_count")==56,"expected_red_sealed":red.get("finding_count")==45,"registered_cells_accounted":len(cells)==70 and len({r.get("cell_id") for r in cells})==70,"no_unaccounted_cells":state.get("registered_cell_count")==70,"inherited_not_fresh":fresh.get("inherited_records_counted_as_fresh")==0,"all_terminals_controller_audit":bool(terminals) and all(r.get("terminal_writer")=="ControllerAudit" for r in terminals),"no_positive_without_support":all(r.get("terminal")=="INSUFFICIENT_EVIDENCE" for r in terminals),"outcome_vault_closed":vault.get("unauthorized_outcome_access")==0,"critic_mutations":critic.get("status")=="PASS" and critic.get("mutations_executed",0)>=75 and critic.get("mutations_rejected")==critic.get("mutations_executed"),"protocol_locked":claim.get("protocol")=="v2.19","package_locked":claim.get("package_version")=="0.2.0b2.dev0","counts_locked":claim.get("issue_derived_repair_count")==6 and claim.get("native_external_repair_count")==4 and claim.get("historical_increment")==0,"no_patch":claim.get("ordinary_patch_count")==0,"no_overclaim":claim.get("prospective_effectiveness")=="NOT_ESTABLISHED" and claim.get("memory_status")=="not demonstrated" and claim.get("production_readiness") is False and claim.get("self_maintaining_software")=="false/not demonstrated" and claim.get("release_boundary")=="PRODUCT_BETA_RC_BLOCKED_EXACT"}
 errors.extend(k for k,v in checks.items() if not v);result={"status":"PASS" if not errors else "BLOCK","checks":checks,"errors":errors,"scientific_status":state.get("status"),"authority_allowed":"Batch102 implementation and evidence integrity audit","authority_forbidden":["patch","repair count","release promotion"]};print(json.dumps(result,sort_keys=True));return 0 if not errors else 1
if __name__=="__main__":raise SystemExit(main())
