"""Seal the Batch103 expected-red audit against the untouched Batch102 boundary."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch103_pre_isomorphism_reactome_closure_expected_failure.json"
BOUNDARY_COMMIT = "17ce08e828dfe5c5c0c77ad162188723af53607b"
INGEST_CHECKPOINT = "ba8631281b75bff89a6b881fb19c0a972a4c8bfb"


def _row(
    finding_id: str,
    path: str,
    symbol: str,
    line_range: str,
    source_authority: str,
    observed: str,
    correction: str,
    test: str,
) -> tuple[str, str, str, str, str, str, str, str]:
    return (
        finding_id,
        path,
        symbol,
        line_range,
        source_authority,
        observed,
        correction,
        test,
    )


FINDINGS = [
    _row(
        "batch102_artifact_not_officially_ingested_at_boundary",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest",
        "official_ingest_boundary",
        "1-1",
        "Batch102 public artifact plus Batch103 prompt contract",
        "The directory did not exist at the untouched Batch102 commit.",
        "Officially ingest the exact 139-entry Batch102 artifact before Batch103 implementation.",
        "test_official_batch102_ingest_receipt_and_exact_identity",
    ),
    _row(
        "master_ledger_missing_reactome_completion_goal",
        "configs/controllergate_master_completion_ledger_v2.json",
        "goals",
        "1-1064",
        "append-only master completion ledger",
        "No goal separately tracks Reactome completion levels R0 through R6.",
        "Append dedicated Reactome source, execution, gain, generalization, and prospective goals.",
        "test_master_ledger_has_batch103_reactome_goals",
    ),
    _row(
        "master_ledger_missing_canonical_isomorphism_reconciliation_goal",
        "configs/controllergate_master_completion_ledger_v2.json",
        "goals",
        "1-1064",
        "append-only master completion ledger",
        "No goal tracks canonical isomorphism reconciliation and errata custody.",
        "Append the canonical-isomorphism reconciliation goal with blockers and evidence.",
        "test_master_ledger_has_canonical_isomorphism_goal",
    ),
    _row(
        "master_ledger_conflates_reactome_structure_and_planning_gain",
        "configs/controllergate_master_completion_ledger_v2.json",
        "CG-GOAL-025-REAL-ARCHITECTURE-ARM-EVALUATION",
        "1001-1038",
        "append-only master completion ledger",
        "The architecture goal does not distinguish source/graph completion from causal-planning gain.",
        "Model structural completion and empirically measured planner gain as separate gates.",
        "test_reactome_structure_and_gain_are_separate_goals",
    ),
    _row(
        "reactome_absent_from_batch102_artifact",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest/extracted_public_artifact",
        "sealed Batch102 member tree",
        "1-139",
        "byte-verified Batch102 artifact member manifest",
        "No Batch102 payload member is a Reactome planner, mapping, decision, or ablation record.",
        "Treat Batch102 as a non-Reactome causal baseline and add new Batch103 records only.",
        "test_batch102_artifact_has_no_reactome_planning_claim",
    ),
    _row(
        "reactome_did_not_select_batch102_cells",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest/extracted_public_artifact/batch102_arm_selection_history_v2.jsonl",
        "arm selection records",
        "1-90",
        "official Batch102 truth-blind selection history",
        "Selection policies contain no Reactome parents or planner decisions.",
        "Preserve the records as baseline A and preregister Reactome-enabled arms.",
        "test_batch102_selection_is_nonreactome_baseline",
    ),
    _row(
        "reactome_did_not_contribute_to_interventions",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest/extracted_public_artifact/batch102_intervention_integrity_audit.json",
        "Batch102 interventions",
        "1-18",
        "official Batch102 intervention audit",
        "No necessity or sufficiency intervention is attributed to Reactome planning.",
        "Create new, frozen, public-safe Reactome planner decisions without relabeling Batch102 history.",
        "test_reactome_interventions_are_batch103_fresh",
    ),
    _row(
        "reactome_did_not_reduce_blocked_cells",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest/extracted_public_artifact/batch102_registered_cell_ledger_v4.jsonl",
        "registered-cell status",
        "1-70",
        "official Batch102 registered-cell ledger",
        "Fifty-two cells remain blocked and no reduction has a Reactome decision parent.",
        "Measure blocked-cell reduction only in a matched Batch103 ablation.",
        "test_reactome_gain_uses_matched_blocked_cell_delta",
    ),
    _row(
        "reactome_did_not_improve_valid_pair_count",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest/extracted_public_artifact/batch102_pair_validity_receipts_v3.jsonl",
        "pair validity",
        "1-9",
        "official Batch102 pair receipts",
        "One pair is valid and eight are invalid without Reactome contribution.",
        "Compare valid-pair yield under equal-budget Reactome-on/off arms.",
        "test_reactome_gain_pair_metric_is_ablated",
    ),
    _row(
        "reactome_did_not_produce_ownership_terminal",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest/extracted_public_artifact/batch102_controller_audit_terminal_records_v5.jsonl",
        "ControllerAudit terminals",
        "1-90",
        "official Batch102 truth-blind terminals",
        "All 90 terminals are INSUFFICIENT_EVIDENCE and contain no ownership fact.",
        "Keep ownership gated by executed causal evidence regardless of Reactome planning.",
        "test_reactome_planner_cannot_write_ownership",
    ),
    _row(
        "reactome_architecture_gain_unmeasured",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest/extracted_public_artifact/batch102_architecture_gain_gate_v4.json",
        "architecture gain gate",
        "1-15",
        "official Batch102 architecture-gain evidence",
        "Reactome-specific architecture gain is not a measured dimension.",
        "Add preregistered per-candidate and per-arm Reactome gain metrics.",
        "test_reactome_architecture_gain_requires_metrics",
    ),
    _row(
        "rpir_coverage_without_causal_planning_value",
        "docs/current_status.md",
        "Reactome release 97 status",
        "813-820",
        "public status plus RPIR v2.1 custody records",
        "Coverage counts exist, but causal-planning value is not established.",
        "Publish an R0-R6 completion model and retain R4 as not established until ablation passes.",
        "test_reactome_completion_model_separates_coverage_from_gain",
    ),
    _row(
        "legacy_chapter_round_robin_primitive_assignment",
        "controllergate/isomorphism/scenarios.py",
        "chapter_scenarios",
        "49-65",
        "current ControllerGate source",
        "Generic primitives are assigned by index slicing across chapter order.",
        "Classify this as a historical synthetic fixture and implement source-grounded selection.",
        "test_current_reactome_scenarios_are_not_round_robin",
    ),
    _row(
        "round_robin_can_be_mistaken_for_isomorphism",
        "controllergate/isomorphism/scenarios.py",
        "chapter_scenarios authority",
        "60-71",
        "current ControllerGate source and public claim boundary",
        "Scenario records call the mapping shadow but do not label its round-robin origin synthetic.",
        "Add an explicit historical-synthetic classification and current-authority firewall.",
        "test_round_robin_fixture_has_no_mapping_authority",
    ),
    _row(
        "source_bound_mapping_uses_synthesized_values",
        "controllergate/isomorphism/value_bound.py",
        "compile_value_bound_candidate",
        "95-181",
        "current RPIR value-binding implementation",
        "Operational candidate fields can be constructed beyond direct Reactome values.",
        "Classify every field origin and forbid synthetic/default values from causal authority.",
        "test_every_reactome_field_has_origin_class",
    ),
    _row(
        "source_bound_fields_use_cross_scenario_fallback",
        "controllergate/isomorphism/source_bound.py",
        "integrated_source_bound_scenario",
        "135-156",
        "current source-bound composition implementation",
        "Missing fields fall back to values from other chapter scenarios.",
        "Record cross-chapter composition explicitly and exclude hidden fallback from claims.",
        "test_cross_chapter_fallback_is_explicit",
    ),
    _row(
        "all_reactome_scenarios_use_plan_maturation",
        "controllergate/isomorphism/runtime.py",
        "execute_structured_scenario",
        "25-30",
        "current structured-scenario runtime",
        "Every structured scenario runs the broad plan_maturation stage.",
        "Implement distinct reaction-specific nonauthorizing operation families.",
        "test_single_plan_maturation_is_retired",
    ),
    _row(
        "reaction_specific_stages_not_independently_executed",
        "controllergate/isomorphism/runtime.py",
        "execute_structured_scenario",
        "71-108",
        "current structured-scenario receipts",
        "One stage receipt covers the scenario rather than independently verified reaction stages.",
        "Emit producer/verifier receipts for each reaction-specific operation.",
        "test_reaction_operations_have_independent_receipts",
    ),
    _row(
        "direct_reactome_and_controllergate_values_not_separated",
        "controllergate/isomorphism/source_bound.py",
        "_actual_event",
        "61-80",
        "RPIR source graph and ControllerGate translation layer",
        "One event object combines resolved source fields with ControllerGate primitive requirements.",
        "Add field-level source and operational authority classifications.",
        "test_direct_and_operational_fields_are_separated",
    ),
    _row(
        "defaults_share_records_with_source_values_without_authority_class",
        "controllergate/isomorphism/value_bound.py",
        "binding records",
        "95-181",
        "current value-binding implementation",
        "Source-derived and operational/default fields lack one mandatory authority-origin registry.",
        "Generate a complete field-grounding registry with claim/planning flags.",
        "test_field_grounding_registry_is_complete",
    ),
    _row(
        "synthetic_values_not_globally_forbidden_from_claims",
        "controllergate/isomorphism/scenarios.py",
        "chapter_scenarios",
        "49-71",
        "public claim-boundary policy",
        "Synthetic round-robin fixtures lack a global claim-bearing prohibition.",
        "Install an authority firewall for SYNTHETIC_TEST_VALUE and CONTROLLERGATE_DEFAULT.",
        "test_synthetic_values_cannot_select_claims",
    ),
    _row(
        "exact_reactome_stoichiometry_incomplete",
        "outputs/post_v2_37_hardening_batch095_provider_orthology_typed_incident_eight_cohort_amds_closure/reactome_release97_stoichiometry_source_audit_v2.json",
        "stoichiometry source audit",
        "1-40",
        "Reactome release 97 structured-source audit",
        "Exact stoichiometry remains unavailable for some mappings.",
        "Keep explicit uncertainty and prevent exact-value claims where source values are absent.",
        "test_missing_stoichiometry_remains_unknown",
    ),
    _row(
        "exact_reaction_timing_incomplete",
        "outputs/post_v2_37_hardening_batch094_value_bound_rpir_fresh_amds_cohort_historical_closure/reactome_timing_annotations.jsonl",
        "reaction timing annotations",
        "1-16814",
        "Reactome release 97 structured-source records",
        "Exact reaction timing is not available for all mappings.",
        "Classify absent timing as unknown and forbid synthesized timing authority.",
        "test_missing_reactome_timing_is_not_defaulted",
    ),
    _row(
        "batch089_source_law_normalized_prompt_not_raw_chapters",
        "configs/batch089_source_document_registry.json",
        "normalized source document registry",
        "1-120",
        "Batch089 append-only source custody",
        "The historical source law is tied to normalized prompt material rather than every raw chapter byte.",
        "Record the limitation without rewriting Batch089 and bind current mappings to RPIR sources.",
        "test_historical_source_normalization_has_errata_receipt",
    ),
    _row(
        "public_docs_omit_reactome_completion_level",
        "README.md",
        "Reactome status summaries",
        "21-43",
        "current public documentation",
        "Coverage and shadow execution are described without an explicit R0-R6 completion level.",
        "Publish structural, planning-gain, generalization, and prospective statuses separately.",
        "test_public_docs_state_reactome_completion_level",
    ),
    _row(
        "reactome_coverage_can_be_misread_as_causal_validation",
        "docs/current_status.md",
        "Reactome coverage summary",
        "813-820",
        "current public documentation",
        "Large pathway/reaction counts appear without a nearby causal-validation firewall.",
        "State that coverage and executable shadow do not establish causal gain.",
        "test_public_docs_reject_coverage_equals_gain",
    ),
    _row(
        "corrected_order_not_bound_to_batch102_planning",
        "configs/controllergate_5_14_6_196_operational_law_v1.json",
        "operational_order",
        "1-20",
        "historical errata and current Batch102 plans",
        "The 5 to 14 to 6 to 196 law exists but Batch102 plan records do not bind it.",
        "Create the v3 canonical stack and test its exact order independently.",
        "test_canonical_5_14_6_196_order_v3",
    ),
    _row(
        "six_set_can_be_misread_as_topology_constructor",
        "configs/controllergate_5_14_6_196_operational_law_v1.json",
        "six-set semantics",
        "1-20",
        "TLD errata plus ControllerGate operational translation",
        "Current authority lacks a CI rejection for six-set construction language.",
        "Lock the six-set to post-topology operation licensing only.",
        "test_six_set_does_not_build_closure",
    ),
    _row(
        "fourteen_set_can_be_misread_as_literal_contacts",
        "configs/controllergate_5_14_6_196_operational_law_v1.json",
        "fourteen-set semantics",
        "1-20",
        "TLD errata plus ControllerGate operational translation",
        "Current authority does not require explicit missing/non-applicable contact slots.",
        "Define a bounded fourteen-slot audit ledger without requiring fourteen source contacts.",
        "test_fourteen_set_is_bounded_audit_not_literal_contacts",
    ),
    _row(
        "one_ninety_six_can_be_misread_as_universal_constant",
        "configs/controllergate_5_14_6_196_operational_law_v1.json",
        "196 proof obligations",
        "1-20",
        "ControllerGate operational translation",
        "Current authority lacks an explicit universal-biology rejection gate.",
        "Define 196 as ControllerGate's 14x14 proof-recurrence schema only.",
        "test_one_ninety_six_is_not_universal_biology",
    ),
    _row(
        "mcm_fourteen_nucleosome_196bp_claim_unsafe",
        "configs/batch089_source_document_registry.json",
        "historical MCM/chromatin statement",
        "1-120",
        "Reactome source custody and current biological claim boundary",
        "The historical exact MCM/fourteen-nucleosome/196-bp statement is factually unsafe.",
        "Add append-only errata: MCM2-7 has six subunits; do not assert the exact nucleosome span.",
        "test_unsafe_mcm_fourteen_196_claim_rejected",
    ),
    _row(
        "brot_terminology_historical_drift",
        "configs/tld_brot_bulb_canonical_law_v1.json",
        "canonical terms",
        "1-15",
        "TLD formal lexicon, errata, and historical ControllerGate usages",
        "TORUS-BROT and ToT-BROT usages are not comprehensively classified.",
        "Audit every active usage and append translation receipts for immutable history.",
        "test_brot_terminology_all_active_usages_classified",
    ),
    _row(
        "tot_bulb_not_tested_as_current_planner_component",
        "configs/tld_brot_bulb_canonical_law_v1.json",
        "ToT-BULB",
        "1-15",
        "TLD formal lexicon and current planner inventory",
        "Environment illumination is documented but not an ablated current planner component.",
        "Keep it observational and test any planner use separately without causal authority.",
        "test_tot_bulb_remains_observational",
    ),
    _row(
        "local_and_cross_family_geometry_conflated",
        "configs/tld_brot_bulb_canonical_law_v1.json",
        "TORUS-BROT and ToT-BROT",
        "1-15",
        "TLD lexicon and ControllerGate operational boundary",
        "Active policy does not enforce local-candidate versus cross-family scope at each usage.",
        "Classify local geometry as TORUS-BROT and coupled cross-family geometry as ToT-BROT.",
        "test_local_and_cross_family_brot_are_distinct",
    ),
    _row(
        "reactome_and_tot_brot_coupling_not_distinguished",
        "docs/BATCH089_FULL_ISOMORPHISM_SOURCE_MAP.md",
        "cross-system mappings",
        "1-120",
        "Reactome pathway structure and TLD coupling terminology",
        "Pathway coupling and ControllerGate cross-system coupling lack an explicit boundary.",
        "Define Reactome structural relations separately from ToT-BROT operational coupling.",
        "test_reactome_pathway_and_tot_brot_coupling_separate",
    ),
    _row(
        "no_source_grounded_reactome_planner",
        "controllergate/amds",
        "planner inventory",
        "1-1",
        "current ControllerGate planner modules",
        "No ReactomePlannerDecisionV1 implementation exists.",
        "Implement a public-safe RPIR planner restricted to registered legal interventions.",
        "test_reactome_planner_uses_only_public_rpir",
    ),
    _row(
        "no_matched_nonreactome_planner_baseline",
        "outputs/post_v2_37_hardening_batch103_reactome_isomorphism_causal_planning_gain_exact_materialization/batch102_official_ingest/extracted_public_artifact/batch102_arm_execution_receipts_v3.jsonl",
        "Batch102 architecture arms",
        "1-6",
        "official Batch102 arm evidence",
        "Batch102 arms are not a preregistered Reactome-on/off comparison.",
        "Freeze canonical AMDS arm A as the matched non-Reactome baseline.",
        "test_reactome_arm_a_is_matched_baseline",
    ),
    _row(
        "no_preregistered_reactome_ablation",
        "configs",
        "planner arm contracts",
        "1-1",
        "current preregistered contract inventory",
        "No frozen A-F plus G-J Reactome planner ablation exists.",
        "Create equal-budget arm contracts and freeze them before outcomes.",
        "test_reactome_arm_contracts_frozen_before_outcomes",
    ),
    _row(
        "no_reactome_gain_threshold",
        "configs/controllergate_master_completion_ledger_v2.json",
        "architecture gain prerequisites",
        "1001-1038",
        "master ledger and Batch103 gain contract",
        "No Reactome-specific two-candidate local gain threshold is recorded.",
        "Preregister the R4 threshold and safety non-regression conditions.",
        "test_reactome_r4_threshold_is_preregistered",
    ),
    _row(
        "no_cross_candidate_reactome_generalization_gate",
        "configs/controllergate_master_completion_ledger_v2.json",
        "goal inventory",
        "1-1064",
        "master completion ledger",
        "No R5 gate spans three candidates, two causal families, and multiple provider classes.",
        "Add a distinct cross-candidate generalization goal and gate.",
        "test_reactome_r5_gate_requires_cross_candidate_scope",
    ),
    _row(
        "no_prospective_reactome_validation_gate",
        "configs/controllergate_master_completion_ledger_v2.json",
        "goal inventory",
        "1-1064",
        "master completion ledger and claim boundary",
        "No future held-out R6 Reactome prospective-validation goal exists.",
        "Add a separate not-run prospective goal that Batch103 cannot pass.",
        "test_reactome_r6_remains_not_run",
    ),
    _row(
        "reactome_shadow_boundary_missing_from_ledger",
        "configs/controllergate_master_completion_ledger_v2.json",
        "goal authority boundaries",
        "1-1064",
        "master ledger and shadow-execution receipts",
        "The nonauthorizing Reactome shadow boundary is not a dedicated completion-ledger constraint.",
        "Persist R3 shadow authority allowed/forbidden fields and reopen conditions.",
        "test_reactome_shadow_is_nonauthorizing_in_ledger",
    ),
    _row(
        "current_status_stale_relative_to_batch102",
        "docs/current_status.md",
        "current batch status",
        "1-70",
        "official Batch102 artifact and current public documentation",
        "The document emphasizes earlier Reactome batches and does not state Batch102's 52 blockers and one valid pair.",
        "Update public status after evidence and retain exact Batch102 baseline counts.",
        "test_current_status_contains_batch102_baseline",
    ),
    _row(
        "isomorphic_language_not_consistently_internal",
        "docs/BATCH089_FULL_ISOMORPHISM_SOURCE_MAP.md",
        "document claim boundary",
        "1-120",
        "public-language policy",
        "Isomorphic terminology is not consistently headed as internal engineering language.",
        "Label current architecture sections INTERNAL DESIGN ANALOGY / OPERATIONAL TRANSLATION.",
        "test_isomorphism_docs_have_internal_design_label",
    ),
    _row(
        "no_canonical_isomorphism_authority_registry",
        "configs",
        "controllergate_isomorphism_registry_v3.jsonl",
        "1-1",
        "Batch103 prompt contract and current registry inventory",
        "No single registry joins source, translation, implementation, experiment, result, evidence level, and blocker.",
        "Create the versioned public-safe canonical isomorphism registry and evidence schema.",
        "test_canonical_isomorphism_registry_complete",
    ),
]


def main() -> int:
    findings = []
    for number, row in enumerate(FINDINGS, 1):
        (
            finding_id,
            path,
            symbol,
            line_range,
            source_authority,
            observed,
            correction,
            test,
        ) = row
        findings.append(
            {
                "finding_number": number,
                "finding_id": finding_id,
                "commit": BOUNDARY_COMMIT,
                "path": path,
                "symbol": symbol,
                "line_range": line_range,
                "source_authority": source_authority,
                "risk": "Coverage or analogy could be overread as empirical causal authority.",
                "observed_batch102_boundary": observed,
                "required_correction": correction,
                "red_to_green_test": test,
            }
        )
    if len(findings) != 45:
        raise RuntimeError(f"expected 45 findings, observed {len(findings)}")
    payload = {
        "status": "BATCH103_PRE_ISOMORPHISM_REACTOME_CLOSURE_FAIL_EXPECTED",
        "boundary_commit": BOUNDARY_COMMIT,
        "official_batch102_ingest_checkpoint": INGEST_CHECKPOINT,
        "finding_count": len(findings),
        "findings": findings,
        "authority_allowed": "expected-red implementation planning",
        "authority_forbidden": [
            "biological proof",
            "causal gain claim",
            "candidate patch",
            "repair count",
            "truth inference",
            "release promotion",
        ],
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    payload["seal_sha256"] = hashlib.sha256(canonical).hexdigest()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        json.dumps(
            {
                "status": payload["status"],
                "finding_count": len(findings),
                "seal_sha256": payload["seal_sha256"],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
