"""Join only verified fresh Batch102 evidence and preserve scientific blockers."""
from __future__ import annotations
import argparse,hashlib,json,random
from collections import Counter,defaultdict
from pathlib import Path
from typing import Any

ROOT=Path(__file__).resolve().parents[1]
DEFAULT_OUT=ROOT/"outputs/post_v2_37_hardening_batch102_fresh_exact_counterfactual_execution_necessity_sufficiency_ownership_closure"
def h(v:Any)->str: return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def fileh(p:Path)->str: return hashlib.sha256(p.read_bytes()).hexdigest()
def loadjl(p:Path)->list[dict]: return [json.loads(x) for x in p.read_text(encoding="utf-8").splitlines() if x.strip()]
def alljl(root:Path,name:str)->list[dict]:
 out=[]
 for p in root.rglob(name):
  try: out.extend(loadjl(p))
  except (OSError,json.JSONDecodeError): pass
 return out
def allj(root:Path,name:str)->list[dict]:
 out=[]
 for p in root.rglob(name):
  try: out.append(json.loads(p.read_text(encoding="utf-8")))
  except (OSError,json.JSONDecodeError): pass
 return out
def writej(out:Path,name:str,v:Any):
 p=out/name; p.parent.mkdir(parents=True,exist_ok=True)
 if isinstance(v,dict): v={"producer":"scripts/finalize_batch102_public_evidence.py","execution_depth":"fresh-evidence join","semantic_scope":"Batch102 public truth-blind campaign","authority_allowed":"evidence reporting at verified depth","authority_forbidden":["fresh execution substitution","patch","repair count","release promotion"],**v}
 p.write_text(json.dumps(v,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")
def writejl(out:Path,name:str,rows:list[dict],scope="Batch102 public truth-blind campaign"):
 if not rows: rows=[{"record_type":"EMPTY_WITH_EXACT_BLOCKER","status":"NOT_ESTABLISHED","exact_blocker":"no_verified_fresh_evidence_for_this_record_family"}]
 enriched=[]
 for row in rows: enriched.append({"producer":"scripts/finalize_batch102_public_evidence.py","execution_depth":"fresh-evidence join","semantic_scope":scope,"authority_allowed":"evidence reporting at verified depth","authority_forbidden":["fresh execution substitution","patch","repair count","release promotion"],**row})
 p=out/name; p.parent.mkdir(parents=True,exist_ok=True); p.write_text("".join(json.dumps(x,sort_keys=True,separators=(",",":"))+"\n" for x in enriched),encoding="utf-8",newline="\n")
def select(policy:dict,cells:list[str],program_for:dict[str,str])->list[str]:
 limit=policy["maximum_envelopes"]; kind=policy["selector"]
 if not limit or not cells: return []
 if kind=="fixed_registered_order": return cells[:limit]
 if kind=="registered_order_stride":
  stride=policy["stride"]; off=policy["offset"]; ordered=[]; i=off
  while len(ordered)<min(limit,len(cells)):
   value=cells[i%len(cells)]; i+=stride
   if value not in ordered: ordered.append(value)
   if i>len(cells)*len(cells)+off: break
  return ordered
 if kind=="stable_hash_rank": return sorted(cells,key=lambda x:h([policy.get("salt"),x]))[:limit]
 if kind=="program_round_robin":
  groups=defaultdict(list)
  for cell in cells: groups[program_for.get(cell,"unknown")].append(cell)
  out=[]
  for index in range(max(map(len,groups.values()),default=0)):
   for key in sorted(groups,key=lambda x:h([policy.get("salt"),x])):
    if index<len(groups[key]) and len(out)<limit: out.append(groups[key][index])
  return out
 return []

def main()->int:
 p=argparse.ArgumentParser(); p.add_argument("--cell-artifacts-root",type=Path,required=True); p.add_argument("--output-root",type=Path,default=DEFAULT_OUT); p.add_argument("--workflow-run-id",default="local-not-dispatched"); p.add_argument("--workflow-head",default="local-not-dispatched"); a=p.parse_args(); out=a.output_root; out.mkdir(parents=True,exist_ok=True)
 programs=loadjl(ROOT/"configs/batch102_candidate_counterfactual_programs_v4.jsonl"); cells=loadjl(ROOT/"configs/batch102_counterfactual_cell_registry_v4.jsonl"); policies=json.loads((ROOT/"configs/batch102_arm_selection_policies_v1.json").read_text(encoding="utf-8"))["policies"]
 fresh=alljl(a.cell_artifacts_root,"batch102_fresh_execution_receipts_v1.jsonl"); broker=alljl(a.cell_artifacts_root,"batch102_broker_operations_v1.jsonl"); accounts=alljl(a.cell_artifacts_root,"batch102_cell_accounting_v1.jsonl"); sources=allj(a.cell_artifacts_root,"batch102_source_capsule_v2.json"); providers=allj(a.cell_artifacts_root,"batch102_provider_capsule_v4.json"); blockers=alljl(a.cell_artifacts_root,"batch102_candidate_blockers_v1.jsonl"); smokes=allj(a.cell_artifacts_root,"batch102_installed_nontld_smoke.json")
 valid_fresh=[r for r in fresh if r.get("execution_epoch")=="BATCH102_FRESH_OPERATION" and str(r.get("workflow_run_id"))==str(a.workflow_run_id) and r.get("workflow_head")==a.workflow_head and r.get("broker_operation_id") and r.get("producer")=="canonical_external_operation_broker" and r.get("record_hash")==h({k:v for k,v in r.items() if k!="record_hash"})]
 by_cell=defaultdict(list)
 for r in valid_fresh: by_cell[r["cell_id"]].append(r)
 reproducible={cid:len(rows)>=2 and len({r["semantic_fingerprint"] for r in rows})==1 for cid,rows in by_cell.items()}
 priorities={"EXECUTED_VERIFIED":5,"EXECUTED_PREDICATE_FALSE":4,"BLOCKED_INCIDENT_PREFLIGHT":3,"BLOCKED_DEPENDENCY_UNAVAILABLE":2,"BLOCKED_EXACT_PROVIDER_UNAVAILABLE":1,"BLOCKED_SOURCE_UNAVAILABLE":0,"SUPERSEDED_WITH_RECEIPT":-1}
 best={}
 for row in accounts:
  if row.get("cell_id") not in best or priorities.get(row.get("status"),-9)>priorities.get(best[row["cell_id"]].get("status"),-9): best[row["cell_id"]]=row
 cell_ledger=[]
 for cell in cells:
  row=best.get(cell["cell_id"],{"status":"BLOCKED_INCIDENT_PREFLIGHT","fresh_receipt_ids":[]})
  cell_ledger.append({"cell_id":cell["cell_id"],"candidate_id":cell["candidate_id"],"program_id":cell["program_id"],"status":row["status"],"fresh_receipt_ids":[r["execution_receipt_id"] for r in by_cell.get(cell["cell_id"],[])],"semantically_reproducible":reproducible.get(cell["cell_id"],False)})
 pair_rows=[]; factorial=[]; sensitivities=[]; necessities=[]; sufficiencies=[]; interactions=[]; alternatives=[]; ownership=[]
 cell_map={r["cell_id"]:r for r in cells}
 for program in programs:
  inc=program["incident_cell"]["cell_id"]; ctl=program["control_cell"]["cell_id"]
  incident=by_cell.get(inc,[]); control=by_cell.get(ctl,[]); valid=len(incident)>=2 and len(control)>=2 and reproducible.get(inc,False) and reproducible.get(ctl,False) and all(r["predicate_result"] for r in incident+control)
  pair={"pair_id":f"pair:{program['program_id']}","program_id":program["program_id"],"candidate_id":program["candidate_id"],"incident_cell_id":inc,"control_cell_id":ctl,"status":"VALID_SINGLE_FACTOR_PAIR" if valid else "PAIR_NOT_VALID","fresh_execution_receipt_ids":[r["execution_receipt_id"] for r in incident+control],"held_invariants_verified":valid}; pair_rows.append(pair)
  factor_cells=[r for r in cells if r["program_id"]==program["program_id"] and r.get("cell_role")=="factorial"]
  complete=bool(factor_cells) and all(len(by_cell.get(r["cell_id"],[]))>=2 and reproducible.get(r["cell_id"],False) for r in factor_cells)
  factorial.append({"factorial_id":f"factorial:{program['program_id']}","program_id":program["program_id"],"registered_corner_count":len(factor_cells),"executed_corner_count":sum(len(by_cell.get(r["cell_id"],[]))>=2 for r in factor_cells),"complete":complete,"status":"VALID_FACTORIAL_DESIGN" if complete else "FACTORIAL_INCOMPLETE"})
  sensitivity=valid and any(r["predicate_result"] for r in incident) and any(r["predicate_result"] for r in control)
  sensitivities.append({"receipt_id":f"sensitivity:{program['program_id']}","program_id":program["program_id"],"supported":sensitivity,"fresh_pair_id":pair["pair_id"]})
  intervention_cells=[r for r in cells if r["program_id"]==program["program_id"] and r.get("cell_role")=="intervention"]
  intervention_ready=bool(intervention_cells) and all(len(by_cell.get(r["cell_id"],[]))>=2 and reproducible.get(r["cell_id"],False) for r in intervention_cells)
  necessities.append({"receipt_id":f"necessity:{program['program_id']}","program_id":program["program_id"],"supported":False,"status":"NOT_ESTABLISHED","exact_blocker":"executed_factor_removal_with_stable_invariants_missing" if not intervention_ready else "intervention_semantics_not_independently_verified"})
  sufficiencies.append({"receipt_id":f"sufficiency:{program['program_id']}","program_id":program["program_id"],"supported":False,"status":"NOT_ESTABLISHED","exact_blocker":"executed_factor_introduction_with_stable_invariants_missing" if not intervention_ready else "intervention_semantics_not_independently_verified"})
  interactions.append({"receipt_id":f"interaction:{program['program_id']}","program_id":program["program_id"],"supported":False,"status":"NOT_ESTABLISHED","factorial_complete":complete,"exact_blocker":"non_additive_estimand_not_independently_supported"})
  alternatives.append({"program_id":program["program_id"],"candidate_id":program["candidate_id"],"unresolved_alternatives":["source","provider","environment_platform","runner","harness_fixture","service_transport","test_expectation","mixed_interaction"],"excluded_alternatives":[],"status":"OPEN"})
  ownership.append({"receipt_id":f"ownership:{program['program_id']}","program_id":program["program_id"],"candidate_id":program["candidate_id"],"ownership_supported":False,"status":"NOT_ESTABLISHED","exact_blocker":"necessity_or_sufficiency_and_alternative_exclusion_not_established"})
 envelopes=[]
 for cid,rows in sorted(by_cell.items()):
  envelope={"envelope_id":f"envelope:{h(cid)[:20]}","cell_id":cid,"program_id":cell_map.get(cid,{}).get("program_id"),"receipt_ids":[r["execution_receipt_id"] for r in rows],"sealed_outcome_hash":h([r["semantic_fingerprint"] for r in rows]),"truth_access":0,"private_tld_access":0}; envelope["envelope_hash"]=h(envelope); envelopes.append(envelope)
 env_by_cell={r["cell_id"]:r for r in envelopes}; program_for={r["cell_id"]:r["program_id"] for r in cells}; available=sorted(env_by_cell); vault=[]; histories=[]; arm_receipts=[]; terminals=[]
 for policy in policies:
  selected=select(policy,available,program_for); history=[]
  for index,cid in enumerate(selected):
   env=env_by_cell[cid]; vault.append({"access_id":f"access:{policy['arm']}:{index}","arm":policy["arm"],"envelope_id":env["envelope_id"],"cell_id":cid,"authorized":True,"selection_index":index,"truth_access":0,"private_tld_access":0}); history.append({"arm":policy["arm"],"selection_index":index,"selected_cell":cid,"opened_envelope":env["envelope_id"],"observation_hash":env["sealed_outcome_hash"],"board_update":"evidence_added_without_authority","information_gain":1.0/(index+1)})
  terminal="INSUFFICIENT_EVIDENCE"; arm_receipts.append({"arm":policy["arm"],"policy":policy["label"],"pre_outcome_plan_hash":h(policy),"selected_cell_count":len(selected),"opened_envelope_count":len(history),"terminal":terminal,"cost":len(history),"information_gain":sum(r["information_gain"] for r in history),"unauthorized_accesses":0})
  histories.extend(history or [{"arm":policy["arm"],"selection_index":None,"selected_cell":None,"opened_envelope":None,"stop_reason":"no_eligible_verified_fresh_outcome"}])
  for program in programs: terminals.append({"candidate_id":program["candidate_id"],"program_id":program["program_id"],"sub_incident":program.get("sub_incident_id"),"arm":policy["arm"],"terminal":"INSUFFICIENT_EVIDENCE","fresh_execution_receipt_ids":[r["execution_receipt_id"] for r in valid_fresh if r["program_id"]==program["program_id"]],"pair_ids":[f"pair:{program['program_id']}"],"sensitivity_receipt_ids":[f"sensitivity:{program['program_id']}"],"necessity_receipt_ids":[f"necessity:{program['program_id']}"],"sufficiency_receipt_ids":[f"sufficiency:{program['program_id']}"],"interaction_receipt_ids":[f"interaction:{program['program_id']}"],"alternative_exclusion_ids":[program["program_id"]],"ownership_facts":[],"unresolved_alternatives":["source","provider","environment_platform","runner","harness_fixture","service_transport","test_expectation","mixed_interaction"],"registered_cells":sum(r["program_id"]==program["program_id"] for r in cells),"executed_cells":sum(r["program_id"]==program["program_id"] and r["cell_id"] in by_cell for r in cells),"blocked_cells":sum(r["program_id"]==program["program_id"] and r["cell_id"] not in by_cell for r in cells),"legal_exhaustion":False,"terminal_writer":"ControllerAudit","authority_allowed":"safe abstention","authority_forbidden":["source ownership","patch","repair count","release"]})
 writejl(out,"batch102_source_capsule_registry_v2.jsonl",sources); writejl(out,"batch102_provider_capsule_registry_v4.jsonl",providers); writejl(out,"batch102_source_version_receipts_v2.jsonl",[{"candidate_id":r.get("candidate_id"),"commit":r.get("full_commit_sha"),"tree":r.get("tree_sha"),"status":"PASS" if r.get("source_capsule_hash") else "BLOCK"} for r in sources]); writejl(out,"batch102_provider_exactness_receipts_v4.jsonl",[{"candidate_id":r.get("candidate_id"),"capsule_id":r.get("capsule_id"),"status":r.get("provider_exactness_status")} for r in providers]); writejl(out,"batch102_fresh_execution_receipts_v1.jsonl",valid_fresh); writejl(out,"batch102_broker_operations_v1.jsonl",broker); writejl(out,"batch102_registered_cell_ledger_v4.jsonl",cell_ledger); writejl(out,"batch102_pair_validity_receipts_v3.jsonl",pair_rows); writejl(out,"batch102_factorial_completeness_receipts_v3.jsonl",factorial); writejl(out,"batch102_dimension_sensitivity_receipts_v3.jsonl",sensitivities); writejl(out,"batch102_necessity_receipts_v3.jsonl",necessities); writejl(out,"batch102_sufficiency_receipts_v3.jsonl",sufficiencies); writejl(out,"batch102_interaction_receipts_v3.jsonl",interactions); writejl(out,"batch102_alternative_exclusion_ledger_v4.jsonl",alternatives); writejl(out,"batch102_ownership_support_receipts_v3.jsonl",ownership); writejl(out,"batch102_outcome_envelopes_v3.jsonl",envelopes); writejl(out,"batch102_outcome_vault_access_log_v3.jsonl",vault); writejl(out,"batch102_arm_execution_receipts_v3.jsonl",[r for r in arm_receipts if r["arm"] in "ABCDEF"]); writejl(out,"batch102_baseline_execution_receipts_v3.jsonl",[r for r in arm_receipts if r["arm"] in "GHIJ"]); writejl(out,"batch102_arm_selection_history_v2.jsonl",histories); writejl(out,"batch102_controller_audit_terminal_records_v5.jsonl",terminals); writejl(out,"batch102_legal_counterfactual_exhaustion_v4.jsonl",[{"program_id":r["program_id"],"legal_exhaustion":False,"exact_blocker":"registered fresh counterfactual inventory not fully executed"} for r in programs]); writejl(out,"batch102_candidate_blockers_v1.jsonl",blockers)
 rawobs=[{"execution_receipt_id":r["execution_receipt_id"],"stdout":r["raw_stdout_object"],"stderr":r["raw_stderr_object"],"return_code":r["raw_return_code"]} for r in valid_fresh]; semobs=[{"execution_receipt_id":r["execution_receipt_id"],"semantic_projection_id":r["semantic_projection_id"],"semantic_fingerprint":r["semantic_fingerprint"],"predicate_result":r["predicate_result"]} for r in valid_fresh]; writejl(out,"batch102_raw_observations_v1.jsonl",rawobs); writejl(out,"batch102_canonical_semantic_observations_v2.jsonl",semobs)
 writej(out,"batch102_fresh_execution_origin_audit.json",{"status":"PASS" if len(valid_fresh)==len(fresh) and bool(valid_fresh) else "BLOCK","fresh_receipt_count":len(valid_fresh),"submitted_receipt_count":len(fresh),"inherited_records_counted_as_fresh":0,"fresh_executed_cell_count":len(by_cell),"fresh_executed_cells_require_two_receipts":True}); writej(out,"batch102_inherited_execution_rejection_control.json",{"status":"PASS","inherited_epoch":"BATCH100_INHERITED_RAW_EXECUTION_BATCH101_REPROJECTION","accepted_as_fresh":False}); writej(out,"batch102_broker_operation_nonempty_audit.json",{"status":"PASS" if valid_fresh and all(r["broker_operation_id"] for r in valid_fresh) else "BLOCK","fresh_receipt_count":len(valid_fresh),"broker_operation_count":len(broker)}); writej(out,"batch102_source_future_commit_exclusion_audit.json",{"status":"PASS" if sources and all(r.get("future_commit_exclusion") is True for r in sources) else "BLOCK","source_capsule_count":len(sources)}); writej(out,"batch102_gold_patch_exclusion_audit.json",{"status":"PASS" if sources and all(r.get("gold_patch_exclusion") is True and r.get("accepted_fix_exclusion") is True for r in sources) else "BLOCK","source_capsule_count":len(sources)}); writej(out,"batch102_provider_prefix_false_parity_control.json",{"status":"PASS","prefix_match_classification":"SERIES_LIMITED_PROVIDER","exact_provider_allowed":False}); writej(out,"batch102_intervention_integrity_audit.json",{"status":"BLOCK" if not any(r["supported"] for r in necessities+sufficiencies) else "PASS","necessity_supported":sum(r["supported"] for r in necessities),"sufficiency_supported":sum(r["supported"] for r in sufficiencies),"source_mutation_count":0,"test_mutation_count":0,"patch_operation_count":0}); writej(out,"batch102_outcome_vault_registry_v3.json",{"status":"PASS","envelope_count":len(envelopes),"policy_hash":fileh(ROOT/"configs/batch102_arm_selection_policies_v1.json"),"opened_envelope_count":len(vault)}); writej(out,"batch102_unselected_outcome_access_audit_v3.json",{"status":"PASS","unauthorized_outcome_access":0}); writej(out,"batch102_architecture_gain_gate_v4.json",{"status":"NOT_ESTABLISHED","architecture_gain":False,"exact_blocker":"private truth join and ownership-grade coverage unavailable"}); writej(out,"batch102_terminal_support_reconstruction_audit_v3.json",{"status":"PASS","terminal_count":len(terminals),"positive_terminal_count":0,"all_terminal_writers_controller_audit":True}); writej(out,"batch102_source_ownership_proof_registry_v1.json",{"status":"NOT_ESTABLISHED","proof_count":0,"exact_blocker":"necessity_or_sufficiency_and_alternative_exclusion_not_established"})
 writej(out,"batch102_public_nontld_installed_smoke_status.json",{"status":"PASS" if len(smokes)>=2 and all(r.get("status")=="PASS" for r in smokes) else "BLOCK","platform_results":smokes,"private_tld_access":0,"truth_access":0,"repair_authority":False}); writej(out,"batch102_preliminary_historical_cohort_registry_status.json",{"status":"IN_PROGRESS","registry_path":"configs/batch102_preliminary_historical_cohort_registry_v1.jsonl","target_count":24}); writej(out,"batch102_prospective_freeze_tooling_status.json",{"status":"PROTOCOL_READY","workflow":"controllergate_prospective_issue_freeze.yml","prospective_validation_run":False}); writej(out,"batch102_external_replication_package_status.json",{"status":"PROTOCOL_READY","package":"docs/batch102_external_replication_package.md","external_replication_occurred":False})
 writej(out,"batch102_historical_manifest_custody_reconciliation.json",{"status":"PASS_WITH_KNOWN_HISTORICAL_MANIFEST_COMPLETENESS_DEFECTS","historical_manifests_rewritten":False,"batch100_known_unlisted_existing_files":["batch100_official_workflow_execution_receipt.json","batch100_independent_semantic_critic_findings.jsonl","batch100_independent_semantic_critic_mutation_controls.json","batch100_independent_semantic_critic_reconstruction.json","batch100_independent_semantic_critic_summary.json","future_protocol_readiness.json"],"batch102_manifest_scope":"Batch102 output directory only","authority_allowed":"disclose historical custody limitation and verify current scoped payload","authority_forbidden":["rewrite historical evidence","claim global historical manifest completeness"]})
 writej(out,"batch102_claim_boundary.json",{"protocol":"v2.19","package_version":"0.2.0b2.dev0","issue_derived_repair_count":6,"native_external_repair_count":4,"historical_increment":0,"ordinary_patch_count":0,"protected_actuation":False,"prospective_effectiveness":"NOT_ESTABLISHED","memory_status":"not demonstrated","full_scoring":"NOT_RUN/disallowed","public_writes":"inactive","automatic_merge":"inactive","release_boundary":"PRODUCT_BETA_RC_BLOCKED_EXACT","production_readiness":False,"self_maintaining_software":"false/not demonstrated"})
 status="BLOCKED_EXACT" if not valid_fresh or not any(r["ownership_supported"] for r in ownership) else "LIMITED_CAUSAL_FEASIBILITY_PENDING_PRIVATE_JOIN"; writej(out,"batch102_consolidated_state.json",{"status":status,"workflow_run_id":a.workflow_run_id,"workflow_head":a.workflow_head,"program_count":len(programs),"registered_cell_count":len(cells),"fresh_executed_cell_count":len(by_cell),"blocked_cell_count":sum(r["status"].startswith("BLOCKED") for r in cell_ledger),"fresh_replay_count":len(valid_fresh),"broker_operation_count":len(broker),"semantically_reproducible_cell_count":sum(reproducible.values()),"valid_single_factor_pair_count":sum(r["status"]=="VALID_SINGLE_FACTOR_PAIR" for r in pair_rows),"valid_factorial_design_count":sum(r["complete"] for r in factorial),"necessity_supported_count":sum(r["supported"] for r in necessities),"sufficiency_supported_count":sum(r["supported"] for r in sufficiencies),"interaction_supported_count":sum(r["supported"] for r in interactions),"ownership_supported_count":sum(r["ownership_supported"] for r in ownership),"unauthorized_outcome_access":0,"exact_blockers":sorted({r.get("blocker","fresh exact evidence incomplete") for r in blockers}) or (["no_verified_fresh_execution_receipts"] if not valid_fresh else ["necessity_sufficiency_alternative_exclusion_not_established"])})
 (out/"campaign_summary.md").write_text(f"# Batch102 fresh-execution closure\n\nStatus: `{status}`\n\nBatch102 joined {len(valid_fresh)} verified fresh receipts across {len(by_cell)} of {len(cells)} registered cells. No candidate patch or repair-count mutation occurred. Necessity, sufficiency, alternative exclusion, causal ownership, architecture gain, prospective effectiveness, memory lift, Product Beta, production readiness, and self-maintaining software remain unestablished unless their explicit records say otherwise.\n",encoding="utf-8",newline="\n")
 print(json.dumps({"status":status,"fresh_receipts":len(valid_fresh),"fresh_cells":len(by_cell),"registered_cells":len(cells),"ownership":sum(r["ownership_supported"] for r in ownership)},sort_keys=True)); return 0
if __name__=="__main__": raise SystemExit(main())
