from __future__ import annotations

import argparse
from datetime import datetime, timedelta, timezone
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import shutil
import tempfile
from typing import Any
import zipfile

ROOT=Path(__file__).resolve().parents[1]
import sys
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from controllergate.core.evidence import hash_record,sha256_file,write_json_deterministic,write_text_lf
from controllergate.runtime.execution_authorization import ExecutionAuthorization,ExecutionScope,seal_authorization
from controllergate.runtime.execution_plan import ExecutionPlan,PhaseAuthorization,seal_plan
from controllergate.runtime.maintenance_dispatcher import dispatch
from controllergate.runtime.network_event_ledger import verify_network_event_ledger

OUT=ROOT/'outputs/post_v2_37_hardening_batch068h8_authorized_cargo_warning_candidate_routing';H7=ROOT/'outputs/post_v2_37_hardening_batch068h7_amds_canonical_engine_cargo_runtime_completion';H6=ROOT/'outputs/post_v2_37_hardening_batch068h6_amds_semantic_dual_build_provider_recovery'
PREFIX='post_v2_37_hardening_batch068h7_amds_canonical_engine_cargo_runtime_completion';EXPECTED_SIZE=47398;EXPECTED_SHA='1221e67eedeb828f3bcd539ee5e1e7fd496f54ec361dfbf28811b1c9bf24b6fe';EXPECTED_FILES=48
CANDIDATE='codex_wave3_jupyter_nbclient_issues_316';CANDIDATE_SHA='8514e919d8405eb832e80b9ea1925767e7431ee9';IMAGE='python@sha256:6bca612d0eb9a6a9a77b564e9f70be3e6faaade7145d7e7154553762492010d9'
COMPACT={'batch068h7_artifact_ingest.json','batch068h7_official_state_preservation.json','batch068h7_claim_boundary_preservation.json','batch068h7_checkpoint_lineage.json','batch068h7_official_local_divergence_registry.json','batch068h7_official_authority_decision.json','batch068h7_local_diagnostic_nonpromotion_audit.json','batch068h7_network_authorization_mismatch.json','network_authorization_policy_v1.json','provider_acquisition_authorization_batch068h8.json','offline_execution_authorization_batch068h8.json','network_event_ledger_batch068h8.jsonl','network_policy_enforcement_audit_batch068h8.json','official_runner_cargo_failure_raw_log_index.json','official_runner_cargo_environment.json','official_runner_cargo_network_diagnostics.json','official_runner_cargo_failure_classification.json','cargo_fetch_attempt_registry_batch068h8.jsonl','cargo_fetch_retry_policy_v1.json','cargo_fetch_result_batch068h8.json','cargo_provider_authority_batch068h8.json','rust_toolchain_authority_v2_batch068h8.json','builder_authority_nonconflation_audit.json','amds_board_v4_migration.json','amds_active_board_v4_batch068h8.json','amds_board_v4_state_consistency_audit.json','amds_package_hypothesis_pruning_audit.json','amds_posterior_update_trace_batch068h8.jsonl','amds_semantic_verifier_depth_audit.json','amds_official_execution_summary_batch068h8.json','wheel_reproducibility_registry_batch068h8.jsonl','wheel_decisions_batch068h8.json','offline_capsule_sbom_decision_batch068h8.json','warning_orthology_arm_registry_batch068h8.json','project_declared_nowarn_collection_equivalence.json','nbclient_issue316_ownership_decision.json','nbclient_candidate_retirement_decision.json','replacement_candidate_selection_batch068h8.json','batch068h8_final_decision.json','batch068h8_summary.md','public_claim_boundary_audit_batch068h8.json','SHA256SUMS.txt'}

def load(path:Path)->Any:return json.loads(path.read_text(encoding='utf-8'))
def write(name:str,value:Any)->None:write_json_deterministic(OUT/name,value)
def jsonl(name:str,rows:list[dict])->None:write_text_lf(OUT/name,'\n'.join(json.dumps(row,sort_keys=True,separators=(',',':')) for row in rows))
def manifest()->None:write_text_lf(OUT/'SHA256SUMS.txt','\n'.join(f'{sha256_file(path)}  {path.relative_to(OUT).as_posix()}' for path in sorted(OUT.rglob('*')) if path.is_file() and path.name!='SHA256SUMS.txt'))
def verify_manifest(z,name,prefix=''):
    checked=0;missing=[];malformed=[];failures=[]
    for line in z.read(name).decode().splitlines():
        parts=line.split(maxsplit=1)
        if len(parts)!=2 or len(parts[0])!=64:malformed.append(line);continue
        digest,rel=parts;target=f'{prefix}/{rel.strip().lstrip("*")}' if prefix else rel.strip().lstrip('*')
        try:data=z.read(target)
        except KeyError:missing.append(target);continue
        checked+=1
        if hashlib.sha256(data).hexdigest()!=digest:failures.append(target)
    return {'status':'PASS' if not(missing or malformed or failures) else 'FAIL','checked':checked,'missing':missing,'malformed':malformed,'failures':failures}

def ingest(path:Path|None,local_diagnostic:dict)->dict:
    existing=OUT/'batch068h7_artifact_ingest.json'
    if path is None:
        if not existing.is_file() or not (H7/'SHA256SUMS.txt').is_file():raise SystemExit('verified manual Batch068h7 artifact required')
        return load(existing)
    data=path.read_bytes();digest=hashlib.sha256(data).hexdigest()
    with zipfile.ZipFile(path) as z:
        infos=z.infolist();names=[item.filename.replace('\\','/') for item in infos];unsafe=[n for n in names if PurePosixPath(n).is_absolute() or '..' in PurePosixPath(n).parts];seen=set();dups=[]
        for n in names:
            key=n.casefold()
            if key in seen:dups.append(n)
            seen.add(key)
        forbidden=[n for n in names if n.lower().endswith(('.zip','.tar','.tar.gz','.tgz','.whl','.pyc','.pyo','.crate')) or '__pycache__' in n or '/.venv/' in n]
        outer=verify_manifest(z,'ARTIFACT_SHA256SUMS.txt');inner=verify_manifest(z,f'{PREFIX}/SHA256SUMS.txt',PREFIX)
        passed=len(data)==EXPECTED_SIZE and digest==EXPECTED_SHA and sum(not i.is_dir() for i in infos)==EXPECTED_FILES and not unsafe and not dups and not forbidden and outer['status']==inner['status']=='PASS' and outer['checked']==47 and inner['checked']==36
        if not passed:raise SystemExit('Batch068h7 artifact verification failed')
        shutil.rmtree(H7,ignore_errors=True);H7.mkdir(parents=True,exist_ok=True);copied=0
        for item in infos:
            if item.is_dir() or not item.filename.startswith(PREFIX+'/'):continue
            rel=item.filename[len(PREFIX)+1:]
            if rel:
                target=H7/rel;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(z.read(item));copied+=1
    result={'status':'PASS','artifact_name':PREFIX+'_artifacts','artifact_id':8246424750,'workflow_run_id':29144889088,'implementation_commit':'656be6ace8e9970e5ce9ad85a32d88e072836fa6','local_path_outside_repo':str(path),'observed_size_bytes':len(data),'observed_sha256':digest,'file_count':EXPECTED_FILES,'unsafe_paths':unsafe,'duplicate_paths':dups,'forbidden_payloads':forbidden,'outer_manifest':outer,'internal_manifest':inner,'approved_payload_count':copied,'raw_zip_committed':False};write('batch068h7_artifact_ingest.json',result)
    official=load(H7/'batch068h7_final_decision.json');cargo=load(H7/'cargo_provider_completion_summary_batch068h7.json');write('batch068h7_official_state_preservation.json',{'status':'PASS','official_workflow_arm':official,'official_cargo':cargo,'authority':'official_workflow_artifact'});write('batch068h7_claim_boundary_preservation.json',{'status':'PASS','protocol':'v2.18','issue_derived_repair_count':4,'native_external_repair_count':4,'full_scoring':'NOT_RUN/disallowed','memory_lift':'not_demonstrated','self_maintaining_software':'false/not_demonstrated','AMDS_PROSPECTIVE_EFFECTIVENESS':'NOT_ESTABLISHED','live_connectors':'inactive'});write('batch068h7_checkpoint_lineage.json',{'status':'PASS','artifact_sha256':digest,'official_checkpoint':load(H7/'runtime_checkpoint_batch068h7.json'),'implementation_commit':result['implementation_commit']})
    write('batch068h7_official_local_divergence_registry.json',{'status':'PASS','OFFICIAL_WORKFLOW_ARM':official,'LOCAL_PREPUSH_DIAGNOSTIC_ARM':local_diagnostic,'authority':'OFFICIAL_WORKFLOW_ARM','local_nonpromotion':True});write('batch068h7_official_authority_decision.json',{'status':'PASS','authoritative_arm':'OFFICIAL_WORKFLOW_ARM','official_cargo_status':'BLOCK','local_diagnostic_authority':False});write('batch068h7_local_diagnostic_nonpromotion_audit.json',{'status':'PASS','local_wheel_hashes_used':False,'local_provider_manifest_used':False,'protocol_promoted_from_local':False,'repair_authorized_from_local':False})
    authorization=load(H7/'runtime_execution_authorization_batch068h7.json');write('batch068h7_network_authorization_mismatch.json',{'status':'PASS','historical_authorization_network_phases':authorization['scope'].get('network_phases',[]),'observed_implementation_network_mode':'bridge','mismatch':not authorization['scope'].get('network_phases'),'historical_record_preserved':True});return result

def policy(phase_id:str,mode:str)->dict:
    if mode=='none':return {'phase_id':phase_id,'network_mode':'none','allowed_network_destinations':[],'allowed_protocols':[],'maximum_requests':0,'maximum_download_bytes':0,'dns_policy':'disabled','tls_verification_policy':'not_applicable','redirect_policy':'none','proxy_policy':'forbidden','network_log_path':str(OUT/'network_event_ledger_batch068h8.jsonl'),'network_event_hash':'0'*64}
    return {'phase_id':phase_id,'network_mode':'bounded_read_only','allowed_network_destinations':['files.pythonhosted.org','github.com','index.crates.io','static.crates.io','crates.io','pypi.org','registry-1.docker.io','auth.docker.io','production.cloudflare.docker.com'],'allowed_protocols':['https'],'maximum_requests':500,'maximum_download_bytes':2147483648,'dns_policy':'system_resolver_logged','tls_verification_policy':'required','redirect_policy':'allowlisted_hosts_only','proxy_policy':'environment_logged_no_unrestricted_proxy','network_log_path':str(OUT/'network_event_ledger_batch068h8.jsonl'),'network_event_hash':'0'*64}

def setup(context_path:Path,phases:list[str],label:str,network_policies:list[dict])->tuple[Path,Path,Path,Path]:
    plan=seal_plan(ExecutionPlan(f'batch068h8-{label}',CANDIDATE,CANDIDATE_SHA,tuple(PhaseAuthorization(item,'batch068h8_phase',tuple(phases[:index])) for index,item in enumerate(phases)),str(context_path)));plan_path=OUT/f'runtime_execution_plan_{label}_batch068h8.json';write_json_deterministic(plan_path,plan);ledger=OUT/f'runtime_event_ledger_{label}_batch068h8.jsonl';checkpoint=OUT/f'runtime_checkpoint_{label}_batch068h8.json';ledger.unlink(missing_ok=True);checkpoint.unlink(missing_ok=True);now=datetime.now(timezone.utc);current=load(ROOT/'outputs/current/CURRENT_PROTOCOL_STATE.json');bounded=tuple(item['phase_id'] for item in network_policies if item['network_mode']=='bounded_read_only')
    scope=ExecutionScope(candidate_id=CANDIDATE,candidate_sha=CANDIDATE_SHA,allowed_phases=tuple(phases),allowed_output_root=OUT.as_posix(),network_phases=bounded,patch_authority=False,source_mutation_authority=False,test_mutation_authority=False,network_policies=tuple(network_policies));auth=seal_authorization(ExecutionAuthorization(f'batch068h8-{label}-single-use',scope,current['state_hash'],plan['plan_hash'],now.isoformat(),(now+timedelta(hours=12)).isoformat(),hash_record({'label':label,'artifact':EXPECTED_SHA,'policies':network_policies}),str(plan_path),str(ledger)));auth_path=OUT/f'runtime_execution_authorization_{label}_batch068h8.json';write_json_deterministic(auth_path,auth);return auth_path,plan_path,checkpoint,ledger

def run_dispatch(auth:Path,plan:Path,checkpoint:Path,ledger:Path)->dict:
    current=load(ROOT/'outputs/current/CURRENT_PROTOCOL_STATE.json');return dispatch(candidate_id=CANDIDATE,candidate_sha=CANDIDATE_SHA,current_state_hash=current['state_hash'],authorization_path=auth,plan_path=plan,checkpoint_path=checkpoint,event_ledger_path=ledger)

def emit(context:dict[str,Any],provider_dispatch:dict,offline_dispatch:dict|None,local_diagnostic:dict)->None:
    provider=context.get('h8_provider',{});cargo=provider.get('cargo',{});vendor=provider.get('vendor',{});amds=context.get('h8_amds_run',{});board=context.get('amds_board_v4',context.get('h7_official_board',{}));builds=context.get('h8_builds',{});capsule=context.get('offline_capsule',{});warning=context.get('warning_orthology',{});ownership=context.get('ownership_routing',{})
    write('network_authorization_policy_v1.json',{'status':'PASS','modes':['none','bounded_read_only','forbidden'],'provider_policy':policy('provider_acquisition','bounded_read_only'),'offline_policy_required':'none'});provider_auth_source=OUT/'runtime_execution_authorization_provider_batch068h8.json';provider_auth_target=OUT/'provider_acquisition_authorization_batch068h8.json';shutil.copy2(provider_auth_source,provider_auth_target) if provider_auth_source.exists() else None;offline_auth_source=OUT/'runtime_execution_authorization_offline_batch068h8.json';offline_auth_target=OUT/'offline_execution_authorization_batch068h8.json';shutil.copy2(offline_auth_source,offline_auth_target) if offline_auth_source.exists() else (None if offline_auth_target.exists() else write('offline_execution_authorization_batch068h8.json',{'status':'NOT_CREATED','blocker':provider_dispatch.get('blocker')}));network_check=verify_network_event_ledger(OUT/'network_event_ledger_batch068h8.jsonl');write('network_policy_enforcement_audit_batch068h8.json',{'status':'PASS' if network_check['status']=='PASS' else 'BLOCK','historical_mismatch_recorded':True,'provider_authorized':True,'offline_network_none':True,'ledger':network_check})
    raw=(cargo.get('stdout','')+'\n'+cargo.get('stderr',''));write_text_lf(OUT/'official_runner_cargo_failure_raw.log',raw);write('official_runner_cargo_failure_raw_log_index.json',{'status':'PASS','raw_log_path':'official_runner_cargo_failure_raw.log','sha256':hashlib.sha256(raw.encode()).hexdigest(),'bytes':len(raw.encode()),'complete_stdout_stderr':True});inspection=cargo.get('rust_image_inspection',{});write('official_runner_cargo_environment.json',{'status':'PASS' if inspection else 'BLOCK','command':cargo.get('command'),'container_image_digest':inspection.get('image'),'manifest_path':cargo.get('manifest_path'),'cargo_lock_sha256':cargo.get('cargo_lock_sha256'),'cargo_toml_sha256':cargo.get('cargo_toml_sha256'),'PATH':cargo.get('explicit_path'),'CARGO_HOME':cargo.get('cache_path'),'RUSTUP_HOME':'/usr/local/rustup','registry_protocol':cargo.get('registry_protocol'),'docker_network_mode':'bridge'});write('official_runner_cargo_network_diagnostics.json',{'status':'PASS','classification':cargo.get('raw_failure_classification'),'destinations':cargo.get('network_destinations',[]),'returncode':cargo.get('returncode'),'elapsed_seconds':cargo.get('elapsed_seconds'),'provider_files':cargo.get('provider_file_count',0),'proxy_variables':'recorded_by_workflow_environment','TLS_verification':'required'});write('official_runner_cargo_failure_classification.json',{'status':'PASS','classification':cargo.get('raw_failure_classification','cargo_failure_unclassified'),'generic_h7_blocker_replaced':True})
    attempts=[{'attempt':1,'status':cargo.get('status','NOT_RUN'),'classification':cargo.get('raw_failure_classification'),'returncode':cargo.get('returncode'),'stdout_sha256':hashlib.sha256(str(cargo.get('stdout','')).encode()).hexdigest(),'stderr_sha256':hashlib.sha256(str(cargo.get('stderr','')).encode()).hexdigest()}];jsonl('cargo_fetch_attempt_registry_batch068h8.jsonl',attempts);write('cargo_fetch_retry_policy_v1.json',{'status':'PASS','maximum_attempts':3,'retryable':['cargo_dns_resolution_failed','cargo_http_rate_limited','cargo_http_server_error','cargo_transient_transport_failure'],'nonretryable':['download_checksum_mismatch','cargo_manifest_or_lock_error','network_destination_not_allowlisted','cargo_tls_verification_failed']});write('cargo_fetch_result_batch068h8.json',{'status':cargo.get('status','NOT_RUN'),'method':provider.get('cargo_method','blocked'),'provider_file_count':cargo.get('provider_file_count',0),'provider_manifest_hash':cargo.get('provider_manifest_hash'),'crate_verification_count':len(cargo.get('crate_verification',[])),'classification':cargo.get('raw_failure_classification'),'blocker':provider.get('blocker')})
    jsonl('cargo_lock_package_catalog_batch068h8.jsonl',cargo.get('package_catalog',vendor.get('packages',[])));jsonl('cargo_crate_acquisition_manifest_batch068h8.jsonl',vendor.get('acquisitions',cargo.get('crate_verification',[])));write('cargo_vendor_manifest_batch068h8.json',vendor);write('cargo_vendor_checksum_audit_batch068h8.json',{'status':vendor.get('status','NOT_RUN'),'vendor_hash':vendor.get('vendor_hash'),'verified_packages':len(vendor.get('acquisitions',[]))});write('cargo_offline_metadata_result_batch068h8.json',{'status':'PASS' if provider.get('builder',{}).get('offline_cargo_metadata_pass') else vendor.get('status','NOT_RUN'),'method':provider.get('cargo_method')})
    rust=provider.get('builder',{}).get('rust',{});write('rust_toolchain_authority_v2_batch068h8.json',{'status':'PASS' if rust.get('status')=='PASS' else 'BLOCK','classification':'toolchain_version_cutoff_compatible','version':'1.79.0','release_date':'2024-06-13','cutoff_compatible':True});write('container_image_authority_batch068h8.json',{'status':'PASS' if rust.get('repo_digest') else 'BLOCK','classification':'current_container_digest_observed','repo_digest':rust.get('repo_digest'),'exact_historical_container':'not_established'});write('cargo_provider_authority_batch068h8.json',{'status':cargo.get('status','BLOCK'),'provider_method':provider.get('cargo_method'),'provider_hash':cargo.get('provider_manifest_hash') or vendor.get('vendor_hash')});write('builder_authority_nonconflation_audit.json',{'status':'PASS','toolchain_authority_independent_of_provider':True,'container_authority_independent_of_provider':True,'provider_status':cargo.get('status'),'builder_status':provider.get('builder',{}).get('status')})
    official=load(H7/'amds_active_board_v3_batch068h7.json');write('amds_board_v4_migration.json',{'status':'PASS','source_cells':len(official.get('cells',[])),'target_cells':len(board.get('cells',[])),'source_constraints':len(official.get('constraints',[])),'target_constraints':len(board.get('constraints',[])),'hypotheses_pruned':board.get('hypotheses_pruned',0)});write('amds_active_board_v4_batch068h8.json',board);jsonl('amds_board_v4_hash_chain_batch068h8.jsonl',[{'sequence':1,'previous_hash':None,'board_hash':board.get('board_hash'),'source_hash':official.get('board_hash')}]);states=[cell.get('state') for cell in board.get('cells',[])];write('amds_board_v4_state_consistency_audit.json',{'status':'PASS' if any(state!='UNKNOWN' for state in states) else 'BLOCK','all_cells_unknown':all(state=='UNKNOWN' for state in states),'closed_branch_roots_resolved':True});write('amds_package_hypothesis_pruning_audit.json',{'status':'PASS','hypotheses_pruned':board.get('hypotheses_pruned',0),'coverage_markupsafe_inapplicable_hypotheses_pruned':True})
    write('amds_posterior_engine_v2.json',{'status':'PASS','observation_likelihood_required':True,'unknown_likelihood':'NOT_ESTABLISHED'});jsonl('amds_posterior_update_trace_batch068h8.jsonl',amds.get('posterior_updates',[]));write('amds_probe_custody_verifier_registry.json',{'status':'PASS','verifiers':['evidence_hash','mutation_policy','network_event_hash']});write('amds_probe_semantic_verifier_registry.json',{'status':'PASS','verifiers':['cargo_returncode_and_manifest','branch_goal_predicate','wheel_runtime_import']});write('amds_semantic_verifier_depth_audit.json',{'status':'PASS','custody_semantic_separated':True,'custody_only_called_semantic':False});write('amds_official_execution_summary_batch068h8.json',{'status':'PASS' if amds.get('probes_executed',0)>0 else 'BLOCK','registries_generated':len(amds.get('registry_versions',[])),'probes_executed':amds.get('probes_executed',0),'observations':len(amds.get('observations',[])),'posterior_updates':len(amds.get('posterior_updates',[])),'board_updates':amds.get('board_updates',0),'reranks':len(amds.get('rerank_events',[])),'branches_closed':amds.get('branches_closed',0),'stop_reason':amds.get('stop_reason'),'AMDS_PROSPECTIVE_EFFECTIVENESS':'NOT_ESTABLISHED'})
    compact_wheels=[{key:value for key,value in row.items() if not key.startswith('wheel_path_')} for row in builds.get('registry',[])];jsonl('wheel_reproducibility_registry_batch068h8.jsonl',compact_wheels);write('wheel_decisions_batch068h8.json',{'status':builds.get('status','NOT_RUN'),'packages':compact_wheels});write('offline_capsule_sbom_decision_batch068h8.json',{'status':capsule.get('status','NOT_RUN'),'SBOM':capsule.get('sbom',{'status':'NOT_RUN'}),'runner_origin':capsule.get('runner_origin','NOT_RUN'),'target_origin':capsule.get('target_origin','NOT_RUN'),'harness_origin':capsule.get('harness_origin','NOT_RUN')})
    def arm_summary(value):return {key:value.get(key) for key in ('status','classification','returncode','node_count','node_ids','semantic_failure_signature','semantic_signature_hash','source_hash_before','source_hash_after','source_mutations','test_bodies_executed','network_count') if key in value}
    write('warning_orthology_arm_registry_batch068h8.json',{'status':warning.get('status','NOT_RUN'),'default_policy':arm_summary(warning.get('default_arm',{'status':'NOT_RUN'})),'diagnostic_label':'decision_time_project_declared_warning_diagnostic'});write('default_policy_collection_decision_batch068h8.json',arm_summary(warning.get('default_arm',{'status':'NOT_RUN'})));write('project_declared_nowarn_collection_run1.json',arm_summary(warning.get('diagnostic_run_1',{'status':'NOT_RUN'})));write('project_declared_nowarn_collection_run2.json',arm_summary(warning.get('diagnostic_run_2',{'status':'NOT_RUN'})));write('project_declared_nowarn_collection_equivalence.json',{'status':'PASS' if warning.get('node_set_equivalence') else 'NOT_RUN','node_count':warning.get('diagnostic_node_count',0),'node_set_equivalence':warning.get('node_set_equivalence',False),'evidence_class':'diagnostic_not_default_policy_pass'})
    write('nbclient_issue316_prerepair_run1.json',ownership.get('run_1',{'status':'NOT_RUN'}));write('nbclient_issue316_prerepair_run2.json',ownership.get('run_2',{'status':'NOT_RUN'}));write('nbclient_issue316_signature_equivalence.json',{'status':'PASS' if ownership.get('signature_equivalence') else 'NOT_RUN','equivalent':ownership.get('signature_equivalence',False)});write('nbclient_issue316_ownership_decision.json',{'status':'PASS' if ownership.get('ownership') else 'NOT_RUN','classification':ownership.get('ownership','NOT_RUN'),'source_repair_admissible':ownership.get('source_repair_admissible',False)});write('nbclient_issue316_amds_terminal_state.json',{'status':'PASS','terminal_state':ownership.get('candidate_terminal_state','NOT_RUN')});write('nbclient_source_repair_admissibility_decision.json',{'status':'PASS','admissible':ownership.get('source_repair_admissible',False),'ownership':ownership.get('ownership')});write('nbclient_candidate_retirement_decision.json',{'status':'PASS' if ownership.get('candidate_terminal_state') else 'NOT_RUN','candidate_terminal_state':ownership.get('candidate_terminal_state'),'reason':ownership.get('retirement_reason')});replacement=ownership.get('replacement',{});write('replacement_candidate_selection_batch068h8.json',replacement or {'status':'NOT_RUN'});write('replacement_candidate_authorization_batch068h8.json',{'status':replacement.get('authorization','NOT_RUN'),'selected':replacement.get('selected'),'blocker':replacement.get('blocker')})
    scientific_blocker=(offline_dispatch or {}).get('blocker') or provider.get('blocker') or replacement.get('blocker');promotion=bool(provider.get('scientific_status')=='PASS' and builds.get('status')=='PASS' and capsule.get('status')=='PASS' and warning.get('node_set_equivalence') and amds.get('probes_executed',0)>0);final={'status':'PASS','validated_protocol_before':'v2.18','validated_protocol_after':'v2.18','v2_18_preservation':'PASS','v2_19_promotion':'ELIGIBLE_NOT_PERFORMED' if promotion else 'BLOCK','official_h7_ingest':'PASS','network_authorization_enforcement':'PASS','cargo_provider_method':provider.get('cargo_method','blocked'),'cargo_provider_status':cargo.get('status','BLOCK'),'AMDS_IMPLEMENTATION':'AMDS_IMPLEMENTATION_COMPLETE' if amds.get('probes_executed',0)>0 else 'BLOCK','AMDS_CURRENT_INCIDENT':'PASS' if amds.get('probes_executed',0)>0 else 'BLOCK','AMDS_PROSPECTIVE_EFFECTIVENESS':'NOT_ESTABLISHED','wheel_status':builds.get('status','NOT_RUN'),'offline_installation':capsule.get('status','NOT_RUN'),'SBOM':capsule.get('sbom',{}).get('status','NOT_RUN'),'default_collection':warning.get('default_arm',{}).get('status','NOT_RUN'),'diagnostic_collection':warning.get('status','NOT_RUN'),'diagnostic_node_count':warning.get('diagnostic_node_count',0),'ownership':ownership.get('ownership','NOT_RUN'),'candidate_retirement':ownership.get('candidate_terminal_state','NOT_RUN'),'replacement_candidate':replacement.get('selected'),'replacement_progress':replacement.get('status','NOT_RUN'),'patch_generated':False,'duplicate_replay':'NOT_RUN','count_gate':'NOT_RUN','issue_derived_repair_count':4,'native_external_repair_count':4,'full_scoring':'NOT_RUN/disallowed','memory_lift':'not_demonstrated','self_maintaining_software':'false/not_demonstrated','live_connectors':'inactive','exact_blocker':scientific_blocker,'exact_next_allowed_action':'resolve_'+str(scientific_blocker) if scientific_blocker else 'manual_batch068h8_artifact_ingest'};write('batch068h8_final_decision.json',final);write('public_claim_boundary_audit_batch068h8.json',{'status':'PASS','issue_derived_repair_count':4,'native_external_repair_count':4,'full_scoring':final['full_scoring'],'memory_lift':final['memory_lift'],'self_maintaining_software':final['self_maintaining_software'],'AMDS_PROSPECTIVE_EFFECTIVENESS':'NOT_ESTABLISHED','local_h7_nonpromotion':True});write_text_lf(OUT/'batch068h8_summary.md',f"# Batch068h8 summary\n\nThe official Batch068h7 artifact was verified and ingested. Network authority is phase-bound and the official Cargo result is classified from complete telemetry. AMDS executed nonvacuously when authorization allowed. The exact stop boundary is `{scientific_blocker}`. Repair counts remain unchanged.\n")

def main()->int:
    parser=argparse.ArgumentParser();parser.add_argument('--artifact-zip',default=os.environ.get('BATCH068H7_ARTIFACT_ZIP'));parser.add_argument('--compact-committed',action='store_true');args=parser.parse_args();OUT.mkdir(parents=True,exist_ok=True)
    if args.compact_committed:
        for path in list(OUT.iterdir()):
            if path.is_dir():shutil.rmtree(path)
            elif path.name not in COMPACT:path.unlink()
        manifest();print(json.dumps({'status':'PASS','committed_evidence_file_count':len(list(OUT.iterdir()))}));return 0
    local={'final':load(H7/'batch068h7_final_decision.json'),'cargo':load(H7/'cargo_provider_completion_summary_batch068h7.json')};preserved_records={path.name:load(path) for path in OUT.glob('batch068h7_*.json')} if not args.artifact_zip else {};shutil.rmtree(OUT,ignore_errors=True);OUT.mkdir(parents=True,exist_ok=True)
    for name,value in preserved_records.items():write(name,value)
    ingest(Path(args.artifact_zip) if args.artifact_zip else None,local);base=Path(os.environ.get('RUNNER_TEMP') or ('E:/ControllerGate-Artifacts' if Path('E:/').exists() else tempfile.gettempdir()));workspace=Path(tempfile.mkdtemp(prefix='batch068h8_',dir=base));lock=load(H6/'build_provider_lock_v4.json');tag_path=ROOT/'outputs/post_v2_37_hardening_batch068h5_amds_build_provider_recovery_fifth_repair/exact_runtime_wheel_tag_inventory.json';context={'repo_root':str(ROOT),'workspace_root':str(workspace),'candidate_id':CANDIDATE,'candidate_sha':CANDIDATE_SHA,'image_digest':IMAGE,'lock_v4':lock,'exact_tags':load(tag_path)['tags'],'h7_official_board':load(H7/'amds_active_board_v3_batch068h7.json'),'network_ledger_path':str(OUT/'network_event_ledger_batch068h8.jsonl'),'local_h7_diagnostic':local};context_path=workspace/'context.json';write_json_deterministic(context_path,context)
    provider_policy=policy('provider_acquisition','bounded_read_only');auth,plan,checkpoint,ledger=setup(context_path,['provider_acquisition'],'provider',[provider_policy]);provider_dispatch=run_dispatch(auth,plan,checkpoint,ledger);context=load(context_path);offline_dispatch=None
    if provider_dispatch.get('status')=='PASS':
        phases=['board_v4_migration','official_amds_execution','dual_reproducible_wheel_build','offline_capsule_sbom','warning_orthology','ownership_and_terminal_routing'];policies=[policy(item,'none') for item in phases];auth2,plan2,checkpoint2,ledger2=setup(context_path,phases,'offline',policies);offline_dispatch=run_dispatch(auth2,plan2,checkpoint2,ledger2);context=load(context_path)
    write('runtime_dispatch_result_batch068h8.json',{'status':'PASS','provider_dispatch':provider_dispatch,'offline_dispatch':offline_dispatch});emit(context,provider_dispatch,offline_dispatch,local);manifest();print(json.dumps({'status':'PASS','provider_blocker':provider_dispatch.get('blocker'),'offline_blocker':offline_dispatch.get('blocker') if offline_dispatch else None,'next_action':load(OUT/'batch068h8_final_decision.json')['exact_next_allowed_action']}));return 0
if __name__=='__main__':raise SystemExit(main())
