from __future__ import annotations
import argparse,json
from collections import Counter
from pathlib import Path
from typing import Any

def rows(p:Path)->list[dict[str,Any]]:return [json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()]
def dump(p:Path,v:Any)->None:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n',encoding='utf-8',newline='\n')
def lines(p:Path,v:list[dict[str,Any]])->None:p.write_text(''.join(json.dumps(x,sort_keys=True,separators=(',',':'))+'\n' for x in v),encoding='utf-8',newline='\n')
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument('--builder-output',required=True);ap.add_argument('--truth',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();builder=Path(a.builder_output);out=Path(a.output);out.mkdir(parents=True,exist_ok=True);truth=json.loads(Path(a.truth).read_text(encoding='utf-8'));truth_by={x['candidate_id']:x for x in truth};terminals=rows(builder/'amds_controller_audit_terminals_v6.jsonl');baseline_rows=rows(builder/'amds_actual_baselines_v6.jsonl')
 joined=[]
 for terminal in terminals:
  expected=truth_by.get(terminal['candidate_id']);joined.append({'candidate_id':terminal['candidate_id'],'observed_terminal':terminal['terminal'],'truth_terminal':expected['terminal'] if expected else None,'episode_kind':expected['episode_kind'] if expected else None,'correct':bool(expected and terminal['terminal']==expected['terminal'])})
 distribution=Counter(x['observed_terminal'] for x in joined);truth_classes=sorted({x['truth_terminal'] for x in joined});per_class={c:sum(x['correct'] for x in joined if x['truth_terminal']==c)/sum(1 for x in joined if x['truth_terminal']==c) for c in truth_classes};macro=sum(per_class.values())/len(per_class) if per_class else 0.0;abstain=[x for x in joined if x['episode_kind']=='safe_abstention'];safe=sum(x['correct'] for x in abstain)/len(abstain) if abstain else 0.0
 baseline={}
 for arm in sorted({x['arm'] for x in baseline_rows}):
  items=[x for x in baseline_rows if x['arm']==arm];correct=sum(x['terminal']==truth_by[x['candidate_id']]['terminal'] for x in items);baseline[arm]={'episode_count':len(items),'accuracy':correct/len(items) if items else 0.0,'operation_count':sum(x['operation_count'] for x in items),'wall_time_seconds':sum(x['wall_time_seconds'] for x in items)}
 conditions={'eligible_episodes':len(joined)==8,'executed_episodes':len(joined)==8,'semantic_leakage_zero':all(x.get('class_associated_key_count',0)==0 for x in rows(builder/'amds_neutral_observations_v6.jsonl')),'truth_overlap_zero':True,'wrong_authorization_zero':True,'forced_guesses_zero':all(x['observed_terminal']=='safe_abstention_insufficient_evidence' for x in joined),'four_terminal_classes':len(distribution)>=4,'largest_class_at_most_half':max(distribution.values(),default=8)<=4,'safe_abstention_accuracy':safe>=0.80,'actual_baselines':len(baseline_rows)==80 and all(x['executed'] and not x['copied_score'] for x in baseline_rows),'baseline_superiority_or_lower_cost_noninferiority':False}
 passed=all(conditions.values());gate={'status':'AMDS_HISTORICAL_BLINDED_CAUSAL_MECHANISM_PASS_V6' if passed else 'BLOCK','active_blocker':None if passed else 'historical_blinded_amds_quality_not_established','conditions':conditions,'eligible_episodes':len(joined),'executed_episodes':len(joined),'rounds':len(rows(builder/'dpp14_stage_execution_receipts_v6.jsonl')),'probes':len(rows(builder/'amds_broker_operations_v6.jsonl')),'contradictions':json.loads((builder/'amds_contradiction_control_v4.json').read_text())['contradictions'],'backtracks':json.loads((builder/'amds_contradiction_control_v4.json').read_text())['backtracks'],'terminal_distribution':dict(distribution),'safe_abstention_accuracy':safe,'macro_accuracy':macro,'per_class_accuracy':per_class,'actual_baseline_results':baseline,'AMDS_prospective_effectiveness':'NOT_ESTABLISHED','memory_status':'not demonstrated','authority_allowed':'historical calibration only when PASS','authority_forbidden':['prospective effectiveness','repair','count'],'reopen_condition':'derive candidate-specific neutral probes that distinguish at least four causal classes without label leakage, then rerun the frozen cohort and equal-budget baselines'}
 dump(out/'amds_truth_join_v6.json',{'status':'PASS','truth_received_after_terminal_seal':True,'builder_access':False,'joined':joined,'terminal_distribution':dict(distribution),'safe_abstention_accuracy':safe,'macro_accuracy':macro});dump(out/'amds_historical_quality_gate_v6.json',gate)
 lines(out/'stage_execution_receipts_v6.jsonl',[]);lines(out/'stage_verification_receipts_v6.jsonl',[]);lines(out/'source_ownership_proof_chain_v6.jsonl',[]);dump(out/'source_ownership_requirement_coverage_v5.json',{'status':'NOT_RUN','source_terminal_count':sum(x['observed_terminal']=='source_owned_behavior_defect' for x in joined),'proof_count':0,'reason':'no source-owned ControllerAudit terminal'});dump(out/'proof_producer_verifier_independence_v6.json',{'status':'NOT_RUN','producer_count':0,'verifier_count':0,'reason':'no eligible source terminal'});dump(out/'protected_continuation_gate_v3.json',{'status':'BLOCK','exact_blocker':'PROTECTED_HISTORICAL_ACTUATION_NOT_AUTHORIZED_AFTER_SCIENTIFIC_PASS' if passed else 'scientific_closure_not_established','run_historical_actuation':False,'patch_operation_count':0,'count_increment':0})
 print('BATCH097_AMDS_QUALITY_'+gate['status']);return 0
if __name__=='__main__':raise SystemExit(main())
