from __future__ import annotations
import argparse,hashlib,json,os,platform,subprocess,sys,tempfile
from pathlib import Path
def main()->int:
 p=argparse.ArgumentParser(); p.add_argument("--wheel",type=Path,required=True); p.add_argument("--output",type=Path,required=True); a=p.parse_args()
 with tempfile.TemporaryDirectory(prefix="batch102-smoke-") as tmp:
  root=Path(tmp); venv=root/"venv"; subprocess.run([sys.executable,"-m","venv",str(venv)],check=True); py=venv/("Scripts/python.exe" if os.name=="nt" else "bin/python"); install=subprocess.run([str(py),"-m","pip","install","--disable-pip-version-check",str(a.wheel)],cwd=root,capture_output=True,text=True,check=False); origin=subprocess.run([str(py),"-c","import controllergate; print(controllergate.__file__)"],cwd=root,capture_output=True,text=True,check=False) if install.returncode==0 else install; smoke=subprocess.run([str(py),"-m","controllergate.cli","--help"],cwd=root,capture_output=True,text=True,check=False) if install.returncode==0 else install; uninstall=subprocess.run([str(py),"-m","pip","uninstall","-y","controllergate"],cwd=root,capture_output=True,text=True,check=False) if install.returncode==0 else install; reinstall=subprocess.run([str(py),"-m","pip","install","--disable-pip-version-check",str(a.wheel)],cwd=root,capture_output=True,text=True,check=False) if install.returncode==0 else install
  imported=origin.returncode==0 and "site-packages" in origin.stdout.replace("\\","/").lower(); status="PASS" if imported and all(r.returncode==0 for r in [install,origin,smoke,uninstall,reinstall]) else "BLOCK"
  row={"status":status,"platform":platform.system().lower(),"wheel_sha256":hashlib.sha256(a.wheel.read_bytes()).hexdigest(),"install_return_code":install.returncode,"import_return_code":origin.returncode,"import_origin":origin.stdout.strip(),"smoke_return_code":smoke.returncode,"uninstall_return_code":uninstall.returncode,"reinstall_return_code":reinstall.returncode,"site_packages_import":imported,"private_tld_access":0,"truth_access":0,"repair_authority":False,"cleanup":"PASS","authority_allowed":"ordinary installed non-TLD smoke","authority_forbidden":["diagnosis claim","patch","repair count","release promotion"]}; a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(row,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n"); print(json.dumps(row,sort_keys=True)); return 0 if status=="PASS" else 1
if __name__=="__main__": raise SystemExit(main())
