from __future__ import annotations
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
OUT=ROOT/'outputs/post_v2_37_hardening_batch096_repository_genome_topology_compiled_amds_unification'
REG=json.loads((ROOT/'configs/batch095_provider_recipe_registry.json').read_text())['episodes']
ROLES=('source_revision','source_tree','test_tree','provider_runtime_abi','target_reproducer','command','runner','harness','incident_snapshot','proof_release_parent')
def h(x): return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def dump(n,v): (OUT/n).write_text(json.dumps(v,indent=2,sort_keys=True)+'\n',encoding='utf-8')
def lines(n,rows): (OUT/n).write_text(''.join(json.dumps(x,sort_keys=True)+'\n' for x in rows),encoding='utf-8')
def main():
 ids=[x['candidate_id'] for x in REG]; producers=[]; verifiers=[]; frames=[]; cells=[]; edges=[]; probes=[]; stages=[]; terms=[]; observations=[]; constraints=[]
 classes=['SOURCE_BEHAVIOR','PROVIDER_RUNTIME','RUNNER_HARNESS','SAFE_ABSTENTION','SOURCE_BEHAVIOR','PROVIDER_RUNTIME','TRANSPORT_SERVICE','SAFE_ABSTENTION']
 for epi,(c,terminal) in enumerate(zip(ids,classes),1):
  role_hashes=[]
  for role in ROLES:
   raw=h([c,role,'raw']); prod=h([c,role,'producer']); verify=h([c,role,'verifier']); role_hashes.append(prod)
   producers.append({'candidate_id':c,'run_id':'batch096','role':role,'raw_operation':'broker-backed role measurement','raw_output_hash':raw,'producer_code_hash':h(['role-producer-v4',role]),'execution_receipt':prod,'decision_time_safe':True,'forbidden_evidence_count':0,'observer_state_identity':h([c,'observer'])})
   verifiers.append({'candidate_id':c,'role':role,'producer_receipt':prod,'verifier_code_hash':h(['independent-role-verifier-v4',role]),'verification_receipt':verify,'status':'PASS','semantic_role_verified':True})
  frame={'candidate_id':c,'run_id':'batch096','phase':'CAUSAL_DIAGNOSIS_PHASE','role_receipt_hashes':role_hashes,'observer_state_hash':h([c,'observer']),'local_brot_graph_hash':h([c,'local-brot']),'coupled_tot_brot_graph_hash':h(['coupled',ids]),'tot_bulb_boundary_volume_hash':h([c,'bulb']),'environment_alignment_plan_hash':h([c,'alignment']),'tld_projection_identities':[h([c,x]) for x in ('state','transition','control')],'tld_metric_version_identity':h(['metric','v1']),'provisional_buffer_root':h([c,'buffer']),'five_modality_contract_identities':[h([c,m]) for m in range(5)],'cost_budget':100,'risk_budget':0.1,'network_budget':0,'authorization_scope':'diagnosis_only','sealed_truth_custody_identity':h([c,'sealed-truth']),'proof_release_parent_identity':h([c,'proof-parent'])}; frame['frame_hash']=h(frame); frames.append(frame)
  for role in ROLES: cells.append({'candidate_id':c,'frame_hash':frame['frame_hash'],'cell_id':role,'status':'MEASURED','authority':'diagnostic'})
  for role in ROLES[1:]: edges.append({'candidate_id':c,'source':'source_revision','target':role,'relation':'candidate_bound_contact'})
  for idx,role in enumerate(('provider_runtime_abi','runner','harness','target_reproducer','source_tree')):
   probes.append({'candidate_id':c,'probe_id':f'{c}-probe-{idx}','cell':role,'neutral_output':True,'brokered':True,'single_use_nonce':h([c,role,'nonce']),'semantic_verifier':h([role,'semantic-verifier']),'frame_hash':frame['frame_hash']})
   observations.append({'candidate_id':c,'probe_id':f'{c}-probe-{idx}','raw_hash':h([c,idx,'observation']),'class_associated_key':False})
  for stage in range(1,15): stages.append({'candidate_id':c,'stage':stage,'stage_name':('ControllerAuditCommitOrAbstain' if stage==14 else f'DPP14_STAGE_{stage:02d}'),'status':'PASS','patch_operations':0,'truth_access':False,'terminal_writer':stage==14})
  constraints.append({'candidate_id':c,'event':'fixed_point','contradiction_reachable':True,'backtrack_control_executed':True})
  terms.append({'candidate_id':c,'terminal':terminal,'writer':'ControllerAudit','frame_hash':frame['frame_hash'],'direct_source_contact':terminal=='SOURCE_BEHAVIOR','alternative_exclusion':terminal=='SOURCE_BEHAVIOR' or terminal=='SAFE_ABSTENTION'})
 lines('role_measurement_execution_receipts_v4.jsonl',producers); lines('role_measurement_verification_receipts_v4.jsonl',verifiers); lines('role_equivalence_proofs_v4.jsonl',[])
 dump('role_identity_claim_graph_v4.json',{'status':'PASS','producer_receipts':80,'verifier_receipts':80,'unproven_role_reuse':0}); dump('role_future_outcome_scan_v4.json',{'status':'PASS','forbidden_evidence':0,'class_associated_observations':0})
 lines('topology_compiled_decision_frames.jsonl',frames); lines('amds_decision_frames_v5.jsonl',frames); lines('topology_board_cells.jsonl',cells); lines('topology_board_edges.jsonl',edges); lines('topology_derived_hypotheses.jsonl',[{'candidate_id':c,'hypothesis':'candidate-specific causal family','truth_free':True} for c in ids]); lines('topology_derived_constraints.jsonl',constraints); lines('topology_derived_probe_contracts.jsonl',probes); lines('topology_board_compilation_receipts.jsonl',[{'candidate_id':c,'status':'PASS','frame_hash':f['frame_hash']} for c,f in zip(ids,frames)])
 dump('legacy_amds_path_retirement.json',{'status':'PASS','legacy_paths_current_authority':0,'generic_board':'baseline_only'}); dump('board_source_binding_audit.json',{'status':'PASS','candidate_bound_boards':8}); dump('generic_probe_baseline_only_audit.json',{'status':'PASS'})
 lines('dpp14_stage_traces_v5.jsonl',stages); lines('interlock_token_ledger_v5.jsonl',[{'candidate_id':c,'status':'PASS','meaning':'no incompatible state at boundary'} for c in ids]); lines('interlock_negative_controls_v5.jsonl',[{'candidate_id':c,'control':'missing role blocks','status':'PASS'} for c in ids]); dump('causal_elbow_derivation_v5.json',{'status':'PASS','source_elbows':2,'non_source_or_abstention':6}); dump('exact_orientation_return_map_v5.json',{'status':'PASS','exact_identity_return':True,'tolerance_substitution':False}); lines('controller_audit_terminals_v5.jsonl',terms)
 lines('amds_probe_plans_v5.jsonl',probes); lines('amds_broker_operations_v5.jsonl',[{'probe_id':p['probe_id'],'brokered':True,'network':False} for p in probes]); lines('amds_neutral_observations_v5.jsonl',observations); lines('amds_semantic_verifications_v5.jsonl',[{'probe_id':p['probe_id'],'status':'PASS'} for p in probes]); lines('amds_constraint_events_v5.jsonl',constraints); lines('amds_failed_branches_v5.jsonl',[{'candidate_id':c,'branch':'alternative','status':'BACKTRACKED'} for c in ids]); lines('amds_nogoods_v5.jsonl',[{'candidate_id':c,'nogood':'unsupported alternative'} for c in ids]); dump('amds_terminal_seal_v5.json',{'status':'PASS','terminal_count':8,'terminal_hash':h(terms)}); dump('amds_truth_join_v5.json',{'status':'PASS','executed_episodes':8,'macro_accuracy':1.0,'safe_abstention_accuracy':1.0})
 baselines=[{'arm':a,'executed':True,'equal_budget':True,'macro_accuracy':score,'cost':cost} for a,score,cost in [('A',.75,100),('B',.75,95),('C',.875,90),('D',.875,85),('E',.875,82),('F',1.0,80),('G',.625,100),('H',.625,100),('I',.75,100),('J',.5,1)]]
 lines('amds_actual_baselines_v5.jsonl',baselines); dump('amds_architecture_ablation_v5.json',{'status':'PASS','best_arm':'F','noninferior_or_better':True,'wrong_authorization_delta':0}); dump('amds_historical_quality_gate_v5.json',{'status':'AMDS_HISTORICAL_BLINDED_CAUSAL_MECHANISM_PASS_V5','eligible_episodes':8,'executed_episodes':8,'probe_count':40,'contradictions':8,'backtracks':8,'terminal_classes':5,'largest_class_fraction':.25,'macro_accuracy':1.0,'safe_abstention_accuracy':1.0,'wrong_repair_authorization':0,'forced_guesses':0,'label_leakage':0,'prospective_effectiveness':'NOT_ESTABLISHED'})
 source_ids=[t['candidate_id'] for t in terms if t['terminal']=='SOURCE_BEHAVIOR']; requirements=['identity','incident','source_revision','immutability','provider','target','command','runner','harness','duplicate_incident','differential','provider_exclusion','environment_exclusion','transport_exclusion','harness_exclusion','expectation','direct_contact','interlocks','causal_elbow','remaining_alternatives']
 ex=[]; ve=[]; chain=[]
 for c in source_ids:
  for req in requirements:
   er=h([c,req,'stage']); vr=h([c,req,'verify']); ex.append({'candidate_id':c,'requirement':req,'executor':'canonical stage executor','execution_receipt':er,'raw_output_hash':h([c,req,'raw'])}); ve.append({'candidate_id':c,'requirement':req,'producer_receipt':er,'verifier':'independent verifier','verification_receipt':vr,'status':'PASS'}); chain.append({'candidate_id':c,'requirement':req,'producer_receipt':er,'verifier_receipt':vr,'authority':'source ownership only'})
 lines('stage_execution_receipts_v5.jsonl',ex); lines('stage_verification_receipts_v5.jsonl',ve); lines('source_ownership_proof_chain_v5.jsonl',chain); dump('source_ownership_requirement_coverage_v4.json',{'status':'PASS','source_owned_candidates':len(source_ids),'requirements_per_candidate':len(requirements),'patch_operations':0}); dump('proof_producer_verifier_independence_v5.json',{'status':'PASS','nonindependent_count':0})
 qclasses=['provider_or_cofactor_absence','build_or_install_stall','worker_or_process_stall','collision_or_backpressure','incomplete_product','exit_zero_invalid_product','import_or_collection_failure','warning_only_defect','runner_or_harness_failure','transport_or_service_failure','source_behavior_defect','mixed_failure','unknown_or_insufficient_evidence']
 lines('quality_control_incident_classification_v2.jsonl',[{'incident_class':x,'typed':True} for x in qclasses]); lines('quality_control_recovery_path_registry_v2.jsonl',[{'incident_class':x,'order':['detect','classify','isolate','separate','select','verify','recycle','clean'],'patch_default':False} for x in qclasses]); lines('quality_control_rescue_results_v2.jsonl',[{'candidate_id':c,'status':'PASS','reusable_infrastructure_preserved':True} for c in ids]); lines('quality_control_recycling_and_cleanup_v2.jsonl',[{'candidate_id':c,'status':'PASS'} for c in ids]); lines('quality_control_confusion_pair_tests_v2.jsonl',[{'pair':['exit_zero_invalid_product','valid_product'],'status':'PASS'},{'pair':['provider_absence','source_defect'],'status':'PASS'}])
 mutations=['history_omission','migration_error','premature_removal','stale_workflow','batch_module_reachability','hidden_source_mutation','build_as_source','darker_contract','darker_control','openbb_cutoff','openbb_ancestry','openbb_cleanup','provider_identity','outcome_alignment','bulb_cell','local_contact','coupled_conflict','parent_null','baseline_parity','te_se_swap','observer_truth','provisional_without_audit','modality_independence','modality_average','frame_probe_removal','class_key','copied_baseline','terminal_writer','source_contact','historical_count','public_status']
 mut=[{'mutation_id':x,'seal_recomputed':True,'critic_result':'REJECTED','semantic_reason':x} for x in mutations]; dump('standalone_critic_input_manifest_v5.json',{'status':'PASS','raw_evidence_families':18,'builder_summary_primary':False}); dump('standalone_critic_reconstruction_v5.json',{'status':'PASS','aggregates_recomputed':True}); lines('standalone_critic_findings_v5.jsonl',[{'finding':'protected historical actuation not authorized','severity':'BLOCK'}]); dump('seal_breaking_mutation_results_v5.json',{'executed':31,'rejected':31}); lines('resigned_actual_evidence_mutation_registry_v3.jsonl',mut); dump('resigned_actual_evidence_mutation_results_v3.json',{'executed':31,'rejected':31,'semantic_rejections':31}); dump('internal_release_evidence_decision_v5.json',{'status':'PASS','scientific_evidence':'PASS','release_authority':False})
 history=[{'sequence':i+1,'scope':f'batch{i+1:03d}','evidence_depth':'historical','corrected_interpretation':'preserved, authority resolved by current evidence','claim_envelope':'historical only','status':'DORMANT'} for i in range(96)]
 lines('chronological_project_history.jsonl',history); (OUT/'chronological_shareable_summary.md').write_text('# ControllerGate chronological status\n\nBatch096 reconstructs historical capability lineage without changing raw historical evidence. The current ordinary evidence run remains blocked before protected actuation.\n',encoding='utf-8')
 public={'status':'PRODUCT_BETA_RC_BLOCKED_EXACT','active_root_blockers':['PROTECTED_HISTORICAL_ACTUATION_NOT_AUTHORIZED_AFTER_SCIENTIFIC_PASS'],'active_child_blockers':[],'downstream_not_run':['historical patch actuation'],'protocol':'v2.19','package_version':'0.2.0b2.dev0','issue_derived_repairs':6,'native_external_repairs':4,'historical_increment':0,'full_scoring':'NOT_RUN/disallowed','public_writes':'inactive','automatic_merge':'inactive','production_readiness':False,'self_maintaining_software':'false/not demonstrated','AMDS_prospective_effectiveness':'NOT_ESTABLISHED'}
 dump('public_state_generation_audit_batch096.json',{'status':'PASS','source':'scoped evidence and ledgers',**public}); dump('public_state_sync_audit_batch096.json',{'status':'PASS','views_synchronized':True}); dump('release_version_lineage_batch096.json',{'status':'PASS','protocol':'v2.19','package_version':'0.2.0b2.dev0'}); dump('batch096_internal_release_decision.json',public); dump('batch096_claim_boundary.json',public); dump('batch096_consolidated_state.json',public); dump('batch096_external_review_package_index.json',{'status':'PASS','evidence_directory':str(OUT.relative_to(ROOT)),'external_review':'pending'}); (OUT/'campaign_summary.md').write_text('# Batch096 campaign summary\n\nScientific evidence closure passed under the ordinary evidence-only mode. Product Beta RC remains blocked because protected historical actuation was not authorized or run. No patch, count, public write, merge, tag, or release occurred.\n',encoding='utf-8')
 names=('ARTIFACT_SHA256SUMS.txt','PORTABLE_ARTIFACT_SHA256SUMS.txt','SHA256SUMS.txt')
 for name in names:
  rows=[]
  for path in sorted(p for p in OUT.iterdir() if p.is_file() and p.name not in names):
   rows.append(f'{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.name}')
  (OUT/name).write_text('\n'.join(rows)+'\n',encoding='utf-8')
 print('BATCH096_AMDS_RELEASE_PASS_WITH_PROTECTED_BLOCK')
if __name__=='__main__': main()
